// src/react/components/BjAvatar.tsx
import type { HTMLAttributes, ReactNode } from 'react'

export interface BjAvatarProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'children'> {
  size?: 'sm' | 'md' | 'lg' | 'xl'
  square?: boolean
  src?: string
  alt?: string
  initials?: string
  icon?: string
  status?: 'online' | 'away' | 'busy' | 'offline'
  children?: ReactNode
}

export function BjAvatar({
  size = 'md',
  square,
  src,
  alt = '',
  initials,
  icon,
  status,
  className,
  children,
  ...rest
}: BjAvatarProps) {
  const cls = [
    'bj-avatar',
    size !== 'md' && `bj-avatar--${size}`,
    square && 'bj-avatar--square',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <span className={cls} {...rest}>
      {src ? <img className="bj-avatar__img" src={src} alt={alt} /> : null}
      {!src && initials ? <span className="bj-avatar__initials">{initials}</span> : null}
      {!src && !initials && icon ? (
        <i className={`bj-avatar__icon ${icon}`} aria-hidden="true" />
      ) : null}
      {!src && !initials && !icon ? children : null}
      {status ? (
        <span className={`bj-avatar__status bj-avatar__status--${status}`} />
      ) : null}
    </span>
  )
}
BjAvatar.displayName = 'BjAvatar'

// src/vue/components/BjAvatar.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface BjAvatarProps {
  size?: 'sm' | 'md' | 'lg' | 'xl'
  square?: boolean
  src?: string
  alt?: string
  initials?: string
  icon?: string
  status?: 'online' | 'away' | 'busy' | 'offline'
}

const props = withDefaults(defineProps<BjAvatarProps>(), {
  size: 'md',
  alt: '',
})

const classes = computed(() => [
  'bj-avatar',
  props.size !== 'md' && `bj-avatar--${props.size}`,
  props.square && 'bj-avatar--square',
])
</script>

<template>
  <span :class="classes" v-bind="$attrs">
    <img v-if="src" class="bj-avatar__img" :src="src" :alt="alt" />
    <span v-else-if="initials" class="bj-avatar__initials">{{ initials }}</span>
    <i v-else-if="icon" class="bj-avatar__icon" :class="icon" aria-hidden="true" />
    <slot v-else />
    <span
      v-if="status"
      class="bj-avatar__status"
      :class="`bj-avatar__status--${status}`"
    />
  </span>
</template>
