// src/react/components/BjBadge.tsx
import type { HTMLAttributes, ReactNode } from 'react'

export interface BjBadgeProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'children'> {
  variant?: 'default' | 'info' | 'success' | 'warning' | 'error' | 'new'
  size?: 'sm' | 'md'
  noIcon?: boolean
  children?: ReactNode
}

export function BjBadge({
  variant = 'default',
  size = 'md',
  noIcon,
  className,
  children,
  ...rest
}: BjBadgeProps) {
  const cls = [
    'bj-badge',
    variant !== 'default' && `bj-badge--${variant}`,
    size === 'sm' && 'bj-badge--sm',
    noIcon && 'bj-badge--no-icon',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <span className={cls} {...rest}>
      {children}
    </span>
  )
}
BjBadge.displayName = 'BjBadge'

// src/vue/components/BjBadge.vue
<script lang="ts">
export interface BjBadgeProps {
  variant?: 'default' | 'info' | 'success' | 'warning' | 'error' | 'new'
  size?: 'sm' | 'md'
  noIcon?: boolean
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<BjBadgeProps>(), {
  variant: 'default',
  size: 'md',
})

const classes = computed(() => [
  'bj-badge',
  props.variant !== 'default' && `bj-badge--${props.variant}`,
  props.size === 'sm' && 'bj-badge--sm',
  props.noIcon && 'bj-badge--no-icon',
])
</script>

<template>
  <span :class="classes" v-bind="$attrs">
    <slot />
  </span>
</template>
