// src/react/components/BjBanner.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react'

export type BjBannerProps = {
  size?: 'sm' | 'md' | 'lg'
  align?: 'left' | 'center' | 'right'
  theme?: 'light' | 'dark' | 'green' | 'yellow' | 'red' | 'plain'
  image?: string
  title?: string
  text?: string
  actions?: ReactNode
  children?: ReactNode
} & ComponentPropsWithoutRef<'div'>

export function BjBanner({
  size = 'md',
  align = 'left',
  theme = 'dark',
  image,
  title,
  text,
  actions,
  children,
  className,
  ...rest
}: BjBannerProps) {
  const cls = [
    'bj-banner',
    size !== 'md' && `bj-banner--${size}`,
    align !== 'left' && `bj-banner--${align}`,
    `bj-banner--${theme}`,
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={cls} {...rest}>
      {image ? (
        <div
          className="bj-banner__img"
          style={{ backgroundImage: `url(${image})` }}
          role="img"
          aria-hidden="true"
        />
      ) : null}
      <div className="bj-banner__overlay" />
      <div className="bj-banner__body">
        {title ? <h1 className="bj-banner__title">{title}</h1> : null}
        {text ? <p className="bj-banner__text">{text}</p> : null}
        {actions ? <div className="bj-banner__actions">{actions}</div> : null}
        {children}
      </div>
    </div>
  )
}

BjBanner.displayName = 'BjBanner'

// src/vue/components/BjBanner.vue
<script lang="ts">
export interface BjBannerProps {
  size?: 'sm' | 'md' | 'lg'
  align?: 'left' | 'center' | 'right'
  theme?: 'light' | 'dark' | 'green' | 'yellow' | 'red' | 'plain'
  image?: string
  title?: string
  text?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<BjBannerProps>(), {
  size: 'md',
  align: 'left',
  theme: 'dark',
})

const classes = computed(() => [
  'bj-banner',
  props.size !== 'md' && `bj-banner--${props.size}`,
  props.align !== 'left' && `bj-banner--${props.align}`,
  `bj-banner--${props.theme}`,
])
</script>

<template>
  <div :class="classes" v-bind="$attrs">
    <div v-if="image" class="bj-banner__img" :style="{ backgroundImage: `url(${image})` }" role="img" aria-hidden="true" />
    <div class="bj-banner__overlay" />
    <div class="bj-banner__body">
      <h1 v-if="title" class="bj-banner__title">{{ title }}</h1>
      <p v-if="text" class="bj-banner__text">{{ text }}</p>
      <div v-if="$slots.actions" class="bj-banner__actions">
        <slot name="actions" />
      </div>
      <slot />
    </div>
  </div>
</template>
