// src/react/components/BjChart.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react'

export type BjChartLegendItem = {
  label: string
  color: string
}

export type BjChartProps = {
  title?: string
  subtitle?: string
  legend?: BjChartLegendItem[]
  actions?: ReactNode
  children?: ReactNode
} & Omit<ComponentPropsWithoutRef<'div'>, 'title'>

export function BjChart({
  title,
  subtitle,
  legend,
  actions,
  children,
  className,
  ...rest
}: BjChartProps) {
  return (
    <div className={['bj-chart', className].filter(Boolean).join(' ')} {...rest}>
      {title || subtitle ? (
        <div className="bj-chart__header">
          <div>
            {title ? <p className="bj-chart__title">{title}</p> : null}
            {subtitle ? <p className="bj-chart__subtitle">{subtitle}</p> : null}
          </div>
          {actions}
        </div>
      ) : null}
      <div className="bj-chart__body">{children}</div>
      {legend?.length ? (
        <div className="bj-chart__legend">
          {legend.map((item) => (
            <span key={item.label} className="bj-chart__legend-item">
              <span className="bj-chart__legend-dot" style={{ backgroundColor: item.color }} />
              {item.label}
            </span>
          ))}
        </div>
      ) : null}
    </div>
  )
}

BjChart.displayName = 'BjChart'

// src/vue/components/BjChart.vue
<script lang="ts">
export interface BjChartLegendItem {
  label: string
  color: string
}

export interface BjChartProps {
  title?: string
  subtitle?: string
  legend?: BjChartLegendItem[]
}
</script>

<script setup lang="ts">
defineProps<BjChartProps>()
</script>

<template>
  <div class="bj-chart" v-bind="$attrs">
    <div v-if="title || subtitle" class="bj-chart__header">
      <div>
        <p v-if="title" class="bj-chart__title">{{ title }}</p>
        <p v-if="subtitle" class="bj-chart__subtitle">{{ subtitle }}</p>
      </div>
      <slot name="actions" />
    </div>
    <div class="bj-chart__body">
      <slot />
    </div>
    <div v-if="legend?.length" class="bj-chart__legend">
      <span v-for="item in legend" :key="item.label" class="bj-chart__legend-item">
        <span class="bj-chart__legend-dot" :style="{ backgroundColor: item.color }" />
        {{ item.label }}
      </span>
    </div>
  </div>
</template>
