// src/react/components/BjCombobox.tsx
import { useCallback, useEffect, useId, useMemo, useRef, useState } from 'react'
import type * as React from 'react'
import { BjSvgIcon } from '../icons'

export interface ComboboxOption {
  value: string
  label: string
  disabled?: boolean
}

export interface BjComboboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'value' | 'defaultValue' | 'onChange' | 'id' | 'children' | 'type'> {
  value?: string
  onValueChange?: (value: string) => void
  label?: string
  hint?: string
  options?: ComboboxOption[]
  error?: boolean
  message?: string
  disabled?: boolean
  placeholder?: string
  noResults?: string
  id?: string
}

export function BjCombobox({
  value = '',
  onValueChange,
  label,
  hint,
  options = [],
  error,
  message,
  disabled,
  placeholder,
  noResults = 'Aucun résultat',
  id: idProp,
  className,
  ...rest
}: BjComboboxProps) {
  const uid = useId()
  const baseId = idProp ?? uid
  const inputId = `${baseId}-input`
  const listboxId = `${baseId}-listbox`

  const [query, setQuery] = useState('')
  const [isOpen, setIsOpen] = useState(false)
  const [activeIndex, setActiveIndex] = useState(-1)
  const wrapperRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  const selectedLabel = useMemo(() => options.find(o => o.value === value)?.label ?? '', [options, value])

  useEffect(() => { setQuery(selectedLabel) }, [selectedLabel])

  const filtered = useMemo(() => {
    const q = query.toLowerCase().trim()
    if (!q) return options
    return options.filter(o => o.label.toLowerCase().includes(q))
  }, [query, options])

  const open = useCallback(() => {
    if (disabled) return
    setIsOpen(true)
    setActiveIndex(-1)
  }, [disabled])

  const close = useCallback(() => {
    setIsOpen(false)
    setActiveIndex(-1)
  }, [])

  const select = useCallback((opt: ComboboxOption) => {
    if (opt.disabled) return
    onValueChange?.(opt.value)
    setQuery(opt.label)
    setIsOpen(false)
    setActiveIndex(-1)
  }, [onValueChange])

  useEffect(() => {
    function onClickOutside(e: MouseEvent) {
      if (isOpen && wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
        close()
        setQuery(selectedLabel)
      }
    }
    document.addEventListener('click', onClickOutside)
    return () => document.removeEventListener('click', onClickOutside)
  }, [isOpen, close, selectedLabel])

  function onInput(e: React.ChangeEvent<HTMLInputElement>) {
    setQuery(e.target.value)
    if (!isOpen) open()
    setActiveIndex(-1)
  }

  function scrollToActive(idx: number) {
    requestAnimationFrame(() => {
      wrapperRef.current?.querySelector(`[data-index="${idx}"]`)?.scrollIntoView({ block: 'nearest' })
    })
  }

  function onKeyDown(e: React.KeyboardEvent) {
    const len = filtered.length
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault()
        if (!isOpen) { open(); return }
        setActiveIndex(prev => { const n = prev < len - 1 ? prev + 1 : 0; scrollToActive(n); return n })
        break
      case 'ArrowUp':
        e.preventDefault()
        if (!isOpen) { open(); return }
        setActiveIndex(prev => { const n = prev > 0 ? prev - 1 : len - 1; scrollToActive(n); return n })
        break
      case 'Enter':
        e.preventDefault()
        if (isOpen && activeIndex >= 0 && activeIndex < len) select(filtered[activeIndex])
        break
      case 'Escape':
        e.preventDefault()
        close()
        setQuery(selectedLabel)
        break
      case 'Tab':
        close()
        break
    }
  }

  const activeDescendant = activeIndex >= 0 ? `${baseId}-opt-${activeIndex}` : undefined
  const hintId = hint ? `${baseId}-hint` : undefined
  const messageId = message ? `${baseId}-msg` : undefined
  const describedBy = [hintId, messageId].filter(Boolean).join(' ') || undefined

  const wrapClass = ['bj-combobox', error && 'bj-combobox--error', isOpen && 'bj-combobox--open', className].filter(Boolean).join(' ')

  return (
    <div ref={wrapperRef} className={wrapClass}>
      {label ? <label className="bj-label" htmlFor={inputId}>{label}</label> : null}
      {hint ? <span id={hintId} className="bj-hint">{hint}</span> : null}

      <div className="bj-combobox__input-wrap">
        <input
          ref={inputRef}
          id={inputId}
          className="bj-combobox__input"
          type="text"
          role="combobox"
          autoComplete="off"
          value={query}
          placeholder={placeholder}
          disabled={disabled}
          aria-expanded={isOpen}
          aria-autocomplete="list"
          aria-haspopup="listbox"
          aria-controls={listboxId}
          aria-activedescendant={activeDescendant}
          aria-invalid={error || undefined}
          aria-describedby={describedBy}
          onChange={onInput}
          onFocus={() => { if (!isOpen) open() }}
          onKeyDown={onKeyDown}
          {...rest}
        />
        <span className="bj-combobox__icon">
          <BjSvgIcon name="arrowDownSLine" />
        </span>
      </div>

      {isOpen && filtered.length > 0 ? (
        <ul id={listboxId} className="bj-combobox__listbox" role="listbox">
          {filtered.map((opt, i) => (
            <li
              key={opt.value}
              id={`${baseId}-opt-${i}`}
              data-index={i}
              className={['bj-combobox__option', i === activeIndex && 'bj-combobox__option--active'].filter(Boolean).join(' ')}
              role="option"
              aria-selected={opt.value === value}
              aria-disabled={opt.disabled || undefined}
              onClick={() => select(opt)}
              onMouseEnter={() => setActiveIndex(i)}
            >
              {opt.label}
            </li>
          ))}
        </ul>
      ) : null}

      {isOpen && filtered.length === 0 ? (
        <div className="bj-combobox__listbox">
          <p className="bj-combobox__no-results">{noResults}</p>
        </div>
      ) : null}

      {message ? (
        <p id={messageId} className={['bj-message', error ? 'bj-message--error' : 'bj-message--info'].filter(Boolean).join(' ')}>
          {message}
        </p>
      ) : null}
    </div>
  )
}

BjCombobox.displayName = 'BjCombobox'

// src/vue/components/BjCombobox.vue
<script lang="ts">
export interface ComboboxOption {
  value: string
  label: string
  disabled?: boolean
}

export interface BjComboboxProps {
  modelValue?: string
  label?: string
  hint?: string
  options?: ComboboxOption[]
  error?: boolean
  message?: string
  disabled?: boolean
  placeholder?: string
  noResults?: string
  id?: string
}
</script>

<script setup lang="ts">
import { ref, computed, watch, nextTick, onMounted, onBeforeUnmount } from 'vue'
import { BjSvgIcon } from '../icons'

let uid = 0

const props = withDefaults(defineProps<BjComboboxProps>(), {
  modelValue: '',
  options: () => [],
  placeholder: '',
  noResults: 'Aucun résultat',
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const comboId = props.id || `bj-combobox-${++uid}`
const inputId = `${comboId}-input`
const listboxId = `${comboId}-listbox`
const hintId = `${comboId}-hint`
const messageId = `${comboId}-msg`

const query = ref('')
const isOpen = ref(false)
const activeIndex = ref(-1)
const wrapperRef = ref<HTMLElement>()
const inputRef = ref<HTMLInputElement>()

const selectedLabel = computed(() => {
  const opt = props.options.find(o => o.value === props.modelValue)
  return opt?.label ?? ''
})

watch(() => props.modelValue, () => {
  query.value = selectedLabel.value
}, { immediate: true })

const filtered = computed(() => {
  const q = query.value.toLowerCase().trim()
  if (!q) return props.options
  return props.options.filter(o => o.label.toLowerCase().includes(q))
})

const describedBy = computed(() => {
  const ids: string[] = []
  if (props.hint) ids.push(hintId)
  if (props.message) ids.push(messageId)
  return ids.length ? ids.join(' ') : undefined
})

function open() {
  if (props.disabled) return
  isOpen.value = true
  activeIndex.value = -1
}

function close() {
  isOpen.value = false
  activeIndex.value = -1
}

function select(opt: ComboboxOption) {
  if (opt.disabled) return
  emit('update:modelValue', opt.value)
  query.value = opt.label
  close()
}

function onInput(e: Event) {
  query.value = (e.target as HTMLInputElement).value
  if (!isOpen.value) open()
  activeIndex.value = -1
}

function onFocus() {
  if (!isOpen.value) open()
}

function onKeydown(e: KeyboardEvent) {
  const len = filtered.value.length
  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault()
      if (!isOpen.value) { open(); return }
      activeIndex.value = activeIndex.value < len - 1 ? activeIndex.value + 1 : 0
      scrollToActive()
      break
    case 'ArrowUp':
      e.preventDefault()
      if (!isOpen.value) { open(); return }
      activeIndex.value = activeIndex.value > 0 ? activeIndex.value - 1 : len - 1
      scrollToActive()
      break
    case 'Home':
      e.preventDefault()
      activeIndex.value = 0
      scrollToActive()
      break
    case 'End':
      e.preventDefault()
      activeIndex.value = len - 1
      scrollToActive()
      break
    case 'Enter':
      e.preventDefault()
      if (isOpen.value && activeIndex.value >= 0 && activeIndex.value < len) {
        select(filtered.value[activeIndex.value])
      }
      break
    case 'Escape':
      e.preventDefault()
      close()
      query.value = selectedLabel.value
      break
    case 'Tab':
      close()
      break
  }
}

function scrollToActive() {
  nextTick(() => {
    const el = wrapperRef.value?.querySelector(`[data-index="${activeIndex.value}"]`)
    el?.scrollIntoView({ block: 'nearest' })
  })
}

function onClickOutside(e: MouseEvent) {
  if (isOpen.value && wrapperRef.value && !wrapperRef.value.contains(e.target as Node)) {
    close()
    query.value = selectedLabel.value
  }
}

onMounted(() => document.addEventListener('click', onClickOutside))
onBeforeUnmount(() => document.removeEventListener('click', onClickOutside))

const activeDescendant = computed(() =>
  activeIndex.value >= 0 ? `${comboId}-opt-${activeIndex.value}` : undefined,
)
</script>

<template>
  <div
    ref="wrapperRef"
    class="bj-combobox"
    :class="[error && 'bj-combobox--error', isOpen && 'bj-combobox--open']"
  >
    <label v-if="label" class="bj-label" :for="inputId">{{ label }}</label>
    <span v-if="hint" :id="hintId" class="bj-hint">{{ hint }}</span>

    <div class="bj-combobox__input-wrap">
      <input
        :id="inputId"
        ref="inputRef"
        class="bj-combobox__input"
        type="text"
        role="combobox"
        autocomplete="off"
        :value="query"
        :placeholder="placeholder"
        :disabled="disabled"
        :aria-expanded="isOpen"
        aria-autocomplete="list"
        aria-haspopup="listbox"
        :aria-controls="isOpen && filtered.length > 0 ? listboxId : undefined"
        :aria-activedescendant="activeDescendant"
        :aria-invalid="error || undefined"
        :aria-describedby="describedBy"
        v-bind="$attrs"
        @input="onInput"
        @focus="onFocus"
        @keydown="onKeydown"
      />
      <span class="bj-combobox__icon"><BjSvgIcon name="arrowDownSLine" /></span>
    </div>

    <ul
      v-if="isOpen && filtered.length > 0"
      :id="listboxId"
      class="bj-combobox__listbox"
      role="listbox"
    >
      <li
        v-for="(opt, i) in filtered"
        :id="`${comboId}-opt-${i}`"
        :key="opt.value"
        :data-index="i"
        class="bj-combobox__option"
        :class="i === activeIndex && 'bj-combobox__option--active'"
        role="option"
        :aria-selected="opt.value === modelValue"
        :aria-disabled="opt.disabled || undefined"
        @click="select(opt)"
        @mouseenter="activeIndex = i"
      >
        {{ opt.label }}
      </li>
    </ul>

    <div v-if="isOpen && filtered.length === 0" class="bj-combobox__listbox">
      <p class="bj-combobox__no-results">{{ noResults }}</p>
    </div>

    <p
      v-if="message"
      :id="messageId"
      class="bj-message"
      :class="error ? 'bj-message--error' : 'bj-message--info'"
      :role="error ? 'alert' : 'status'"
    >
      {{ message }}
    </p>
  </div>
</template>
