// src/react/components/BjDropdown.tsx
import { useCallback, useEffect, useId, useRef, useState, type ReactNode } from 'react'

export interface BjDropdownProps {
  align?: 'left' | 'right'
  direction?: 'down' | 'up'
  size?: 'sm' | 'md'
  trigger: ReactNode
  children?: ReactNode
  className?: string
}

export function BjDropdown({
  align = 'left',
  direction = 'down',
  size = 'md',
  trigger,
  children,
  className,
}: BjDropdownProps) {
  const [isOpen, setIsOpen] = useState(false)
  const wrapperRef = useRef<HTMLDivElement>(null)
  const triggerRef = useRef<HTMLButtonElement>(null)
  const menuRef = useRef<HTMLUListElement>(null)
  const baseId = useId()
  const menuId = `bj-dropdown-menu-${baseId.replace(/:/g, '')}`

  const open = useCallback(() => {
    setIsOpen(true)
    requestAnimationFrame(() => {
      const first = menuRef.current?.querySelector<HTMLElement>('[role="menuitem"]:not([aria-disabled="true"])')
      first?.focus()
    })
  }, [])

  const close = useCallback(() => {
    setIsOpen(false)
  }, [])

  const toggle = useCallback(() => {
    if (isOpen) close()
    else open()
  }, [isOpen, open, close])

  useEffect(() => {
    function onClickOutside(e: MouseEvent) {
      if (isOpen && wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
        close()
      }
    }
    document.addEventListener('click', onClickOutside)
    return () => document.removeEventListener('click', onClickOutside)
  }, [isOpen, close])

  function getItems(): HTMLElement[] {
    if (!menuRef.current) return []
    return Array.from(menuRef.current.querySelectorAll<HTMLElement>('[role="menuitem"]:not([aria-disabled="true"])'))
  }

  function onTriggerKeydown(e: React.KeyboardEvent) {
    if (['ArrowDown', 'ArrowUp', 'Enter', ' '].includes(e.key)) {
      e.preventDefault()
      if (!isOpen) open()
    }
  }

  function onMenuKeydown(e: React.KeyboardEvent) {
    const items = getItems()
    const idx = items.indexOf(document.activeElement as HTMLElement)

    switch (e.key) {
      case 'ArrowDown': {
        e.preventDefault()
        const next = idx < items.length - 1 ? idx + 1 : 0
        items[next]?.focus()
        break
      }
      case 'ArrowUp': {
        e.preventDefault()
        const prev = idx > 0 ? idx - 1 : items.length - 1
        items[prev]?.focus()
        break
      }
      case 'Home': {
        e.preventDefault()
        items[0]?.focus()
        break
      }
      case 'End': {
        e.preventDefault()
        items[items.length - 1]?.focus()
        break
      }
      case 'Escape': {
        e.preventDefault()
        close()
        triggerRef.current?.focus()
        break
      }
      case 'Tab': {
        close()
        break
      }
    }
  }

  return (
    <div
      ref={wrapperRef}
      className={[
        'bj-dropdown',
        align === 'right' && 'bj-dropdown--right',
        direction === 'up' && 'bj-dropdown--up',
        size === 'sm' && 'bj-dropdown--sm',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
    >
      <button
        ref={triggerRef}
        type="button"
        className="bj-dropdown__trigger"
        aria-haspopup="menu"
        aria-expanded={isOpen}
        aria-controls={isOpen ? menuId : undefined}
        onClick={e => {
          e.stopPropagation()
          toggle()
        }}
        onKeyDown={onTriggerKeydown}
      >
        {trigger}
      </button>
      {isOpen ? (
        <ul
          ref={menuRef}
          id={menuId}
          className="bj-dropdown__menu"
          data-bj-expanded
          role="menu"
          style={{ display: 'block' }}
          onKeyDown={onMenuKeydown}
        >
          {children}
        </ul>
      ) : null}
    </div>
  )
}

BjDropdown.displayName = 'BjDropdown'

// src/vue/components/BjDropdown.vue
<script lang="ts">
export interface BjDropdownProps {
  align?: 'left' | 'right'
  direction?: 'down' | 'up'
  size?: 'sm' | 'md' | 'lg'
}
</script>

<script setup lang="ts">
import { computed, ref, nextTick, onMounted, onBeforeUnmount } from 'vue'

let uid = 0

const props = withDefaults(defineProps<BjDropdownProps>(), {
  align: 'left',
  direction: 'down',
  size: 'md',
})

const emit = defineEmits<{
  open: []
  close: []
  select: [value: string]
}>()

const isOpen = ref(false)
const wrapperRef = ref<HTMLElement>()
const triggerRef = ref<HTMLButtonElement>()
const menuId = `bj-dropdown-menu-${++uid}`

const classes = computed(() => [
  'bj-dropdown',
  props.align === 'right' && 'bj-dropdown--right',
  props.direction === 'up' && 'bj-dropdown--up',
  props.size === 'sm' && 'bj-dropdown--sm',
  props.size === 'lg' && 'bj-dropdown--lg',
])

function getMenuItems(): HTMLElement[] {
  if (!wrapperRef.value) return []
  return Array.from(wrapperRef.value.querySelectorAll<HTMLElement>('[role="menuitem"]'))
}

function open() {
  isOpen.value = true
  emit('open')
  nextTick(() => {
    const items = getMenuItems()
    if (items.length) items[0].focus()
  })
}

function close(restoreFocus = true) {
  isOpen.value = false
  emit('close')
  if (restoreFocus) nextTick(() => triggerRef.value?.focus())
}

function toggle() {
  if (isOpen.value) close()
  else open()
}

function onTriggerKeydown(e: KeyboardEvent) {
  if (['ArrowDown', 'ArrowUp', 'Enter', ' '].includes(e.key)) {
    e.preventDefault()
    if (!isOpen.value) open()
  }
}

function onMenuKeydown(e: KeyboardEvent) {
  const items = getMenuItems()
  const current = items.indexOf(document.activeElement as HTMLElement)

  switch (e.key) {
    case 'ArrowDown': {
      e.preventDefault()
      const next = current < items.length - 1 ? current + 1 : 0
      items[next]?.focus()
      break
    }
    case 'ArrowUp': {
      e.preventDefault()
      const prev = current > 0 ? current - 1 : items.length - 1
      items[prev]?.focus()
      break
    }
    case 'Home': {
      e.preventDefault()
      items[0]?.focus()
      break
    }
    case 'End': {
      e.preventDefault()
      items[items.length - 1]?.focus()
      break
    }
    case 'Escape': {
      e.preventDefault()
      close()
      break
    }
    case 'Tab': {
      close(false)
      break
    }
  }
}

function onClickOutside(e: MouseEvent) {
  if (isOpen.value && wrapperRef.value && !wrapperRef.value.contains(e.target as Node)) {
    close(false)
  }
}

onMounted(() => document.addEventListener('click', onClickOutside))
onBeforeUnmount(() => document.removeEventListener('click', onClickOutside))

defineExpose({ open, close, toggle, isOpen })
</script>

<template>
  <div ref="wrapperRef" :class="classes" v-bind="$attrs">
    <button
      ref="triggerRef"
      type="button"
      class="bj-dropdown__trigger"
      aria-haspopup="menu"
      :aria-expanded="isOpen"
      :aria-controls="isOpen ? menuId : undefined"
      @click.stop="toggle"
      @keydown="onTriggerKeydown"
    >
      <slot name="trigger" />
    </button>
    <ul
      v-if="isOpen"
      :id="menuId"
      class="bj-dropdown__menu"
      data-bj-expanded
      role="menu"
      style="display: block"
      @keydown="onMenuKeydown"
    >
      <slot />
    </ul>
  </div>
</template>
