// src/react/components/BjFooter.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react'

export type BjFooterProps = {
  top?: ReactNode
  bottom?: ReactNode
  children?: ReactNode
} & ComponentPropsWithoutRef<'footer'>

export function BjFooter({ top, bottom, children, className, ...rest }: BjFooterProps) {
  return (
    <footer className={['bj-footer', className].filter(Boolean).join(' ')} {...rest}>
      {top ? (
        <div className="bj-footer__top">
          <div className="bj-container">{top}</div>
        </div>
      ) : null}
      <div className="bj-footer__bottom">
        <div className="bj-container">
          {bottom}
          {children}
        </div>
      </div>
    </footer>
  )
}

BjFooter.displayName = 'BjFooter'

// src/vue/components/BjFooter.vue
<template>
  <footer class="bj-footer" v-bind="$attrs">
    <div v-if="$slots.top" class="bj-footer__top">
      <div class="bj-container">
        <slot name="top" />
      </div>
    </div>
    <div class="bj-footer__bottom">
      <div class="bj-container">
        <slot name="bottom" />
        <slot />
      </div>
    </div>
  </footer>
</template>
