// src/react/components/BjGallery.tsx
import { useCallback, useEffect, useState, type KeyboardEvent as ReactKeyboardEvent } from 'react'
import { createPortal } from 'react-dom'

export type GalleryImage = {
  src: string
  alt?: string
  caption?: string
  thumbnail?: string
}

export interface BjGalleryProps {
  images: GalleryImage[]
  cols?: 2 | 3 | 4
  className?: string
}

export function BjGallery({ images, cols = 3, className }: BjGalleryProps) {
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [currentIndex, setCurrentIndex] = useState(0)

  const current = images[currentIndex]

  const openLightbox = useCallback((index: number) => {
    setCurrentIndex(index)
    setLightboxOpen(true)
    document.body.classList.add('bj-modal-open')
  }, [])

  const closeLightbox = useCallback(() => {
    setLightboxOpen(false)
    document.body.classList.remove('bj-modal-open')
  }, [])

  const prev = useCallback(() => {
    setCurrentIndex(i => (i > 0 ? i - 1 : images.length - 1))
  }, [images.length])

  const next = useCallback(() => {
    setCurrentIndex(i => (i < images.length - 1 ? i + 1 : 0))
  }, [images.length])

  useEffect(() => {
    function onKeydown(e: globalThis.KeyboardEvent) {
      if (!lightboxOpen) return
      if (e.key === 'Escape') closeLightbox()
      else if (e.key === 'ArrowLeft') prev()
      else if (e.key === 'ArrowRight') next()
    }
    document.addEventListener('keydown', onKeydown)
    return () => document.removeEventListener('keydown', onKeydown)
  }, [lightboxOpen, closeLightbox, prev, next])

  useEffect(() => {
    return () => {
      document.body.classList.remove('bj-modal-open')
    }
  }, [])

  function onItemKeyDown(e: ReactKeyboardEvent<HTMLDivElement>, index: number) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault()
      openLightbox(index)
    }
  }

  const lightbox =
    lightboxOpen && current ? (
      <div
        className="bj-lightbox"
        data-bj-expanded
        role="dialog"
        aria-label="Visionneuse d'images"
        style={{ display: 'flex' }}
        onClick={e => {
          if (e.target === e.currentTarget) closeLightbox()
        }}
        onKeyDown={e => {
          if (e.key === 'Escape') closeLightbox()
        }}
      >
        <span className="bj-lightbox__counter">
          {currentIndex + 1} / {images.length}
        </span>
        <button type="button" className="bj-lightbox__close" aria-label="Fermer" onClick={closeLightbox}>
          <i className="ri-close-line" aria-hidden="true" />
        </button>
        <button
          type="button"
          className="bj-lightbox__nav bj-lightbox__nav--prev"
          aria-label="Image précédente"
          onClick={prev}
        >
          <i className="ri-arrow-left-s-line" aria-hidden="true" />
        </button>
        <div className="bj-lightbox__content">
          <img className="bj-lightbox__img" src={current.src} alt={current.alt ?? ''} />
          {current.caption ? <p className="bj-lightbox__caption">{current.caption}</p> : null}
        </div>
        <button
          type="button"
          className="bj-lightbox__nav bj-lightbox__nav--next"
          aria-label="Image suivante"
          onClick={next}
        >
          <i className="ri-arrow-right-s-line" aria-hidden="true" />
        </button>
      </div>
    ) : null

  return (
    <>
      <div
        className={['bj-gallery', cols !== 3 && `bj-gallery--cols-${cols}`, className]
          .filter(Boolean)
          .join(' ')}
      >
        {images.map((img, i) => (
          <div
            key={`${img.src}-${i}`}
            className="bj-gallery__item"
            role="button"
            tabIndex={0}
            aria-label={`Voir l'image ${i + 1}`}
            onClick={() => openLightbox(i)}
            onKeyDown={e => onItemKeyDown(e, i)}
          >
            <img className="bj-gallery__img" src={img.thumbnail || img.src} alt={img.alt ?? ''} />
            {img.caption ? <span className="bj-gallery__caption">{img.caption}</span> : null}
          </div>
        ))}
      </div>
      {lightbox ? createPortal(lightbox, document.body) : null}
    </>
  )
}

BjGallery.displayName = 'BjGallery'

// src/vue/components/BjGallery.vue
<script setup lang="ts">
import { computed, ref, onMounted, onBeforeUnmount } from 'vue'

export interface GalleryImage {
  src: string
  alt?: string
  caption?: string
  thumbnail?: string
}

export interface BjGalleryProps {
  images: GalleryImage[]
  cols?: 2 | 3 | 4
}

const props = withDefaults(defineProps<BjGalleryProps>(), {
  cols: 3,
})

const lightboxOpen = ref(false)
const currentIndex = ref(0)

const galleryClasses = computed(() => [
  'bj-gallery',
  props.cols !== 3 && `bj-gallery--cols-${props.cols}`,
])

const current = computed(() => props.images[currentIndex.value])

function openLightbox(index: number) {
  currentIndex.value = index
  lightboxOpen.value = true
  document.body.classList.add('bj-modal-open')
}

function closeLightbox() {
  lightboxOpen.value = false
  document.body.classList.remove('bj-modal-open')
}

function prev() {
  currentIndex.value = currentIndex.value > 0 ? currentIndex.value - 1 : props.images.length - 1
}

function next() {
  currentIndex.value = currentIndex.value < props.images.length - 1 ? currentIndex.value + 1 : 0
}

function onKeydown(e: KeyboardEvent) {
  if (!lightboxOpen.value) return
  if (e.key === 'Escape') closeLightbox()
  else if (e.key === 'ArrowLeft') prev()
  else if (e.key === 'ArrowRight') next()
}

onMounted(() => document.addEventListener('keydown', onKeydown))
onBeforeUnmount(() => {
  document.removeEventListener('keydown', onKeydown)
  document.body.classList.remove('bj-modal-open')
})
</script>

<template>
  <div :class="galleryClasses" v-bind="$attrs">
    <div
      v-for="(img, i) in images"
      :key="i"
      class="bj-gallery__item"
      role="button"
      tabindex="0"
      :aria-label="`Voir l'image ${i + 1}`"
      @click="openLightbox(i)"
      @keydown.enter="openLightbox(i)"
    >
      <img class="bj-gallery__img" :src="img.thumbnail || img.src" :alt="img.alt || ''" />
      <span v-if="img.caption" class="bj-gallery__caption">{{ img.caption }}</span>
    </div>
  </div>

  <Teleport to="body">
    <div
      v-if="lightboxOpen"
      class="bj-lightbox"
      data-bj-expanded
      role="dialog"
      aria-label="Visionneuse d'images"
      style="display: flex"
      @click.self="closeLightbox"
    >
      <span class="bj-lightbox__counter">{{ currentIndex + 1 }} / {{ images.length }}</span>
      <button class="bj-lightbox__close" aria-label="Fermer" @click="closeLightbox">
        <i class="ri-close-line" aria-hidden="true" />
      </button>
      <button class="bj-lightbox__nav bj-lightbox__nav--prev" aria-label="Image précédente" @click="prev">
        <i class="ri-arrow-left-s-line" aria-hidden="true" />
      </button>
      <div class="bj-lightbox__content">
        <img class="bj-lightbox__img" :src="current.src" :alt="current.alt || ''" />
        <p v-if="current.caption" class="bj-lightbox__caption">{{ current.caption }}</p>
      </div>
      <button class="bj-lightbox__nav bj-lightbox__nav--next" aria-label="Image suivante" @click="next">
        <i class="ri-arrow-right-s-line" aria-hidden="true" />
      </button>
    </div>
  </Teleport>
</template>
