// src/react/components/BjLink.tsx
import { forwardRef, type AnchorHTMLAttributes, type ReactNode } from 'react'

import { BjSvgIcon } from '../icons'

export interface BjLinkProps extends Omit<AnchorHTMLAttributes<HTMLAnchorElement>, 'children'> {
  size?: 'sm' | 'md' | 'lg'
  iconPosition?: 'left' | 'right' | 'none'
  reset?: boolean
  external?: boolean
  children?: ReactNode
}

export const BjLink = forwardRef<HTMLAnchorElement, BjLinkProps>(
  ({ size = 'md', iconPosition = 'none', reset, external, className, children, target, rel, ...rest }, ref) => {
    const cls = [
      'bj-link',
      size !== 'md' && `bj-link--${size}`,
      iconPosition === 'left' && 'bj-link--icon-left',
      iconPosition === 'right' && 'bj-link--icon-right',
      reset && 'bj-link--reset',
      className,
    ]
      .filter(Boolean)
      .join(' ')

    const effectiveTarget = external ? '_blank' : target
    const effectiveRel = external ? 'noopener noreferrer' : rel

    return (
      <a ref={ref} className={cls} target={effectiveTarget} rel={effectiveRel} {...rest}>
        {children}
        {external ? (
          <BjSvgIcon name="externalLinkLine" aria-hidden="true" />
        ) : null}
      </a>
    )
  }
)
BjLink.displayName = 'BjLink'

// src/vue/components/BjLink.vue
<script lang="ts">
export interface BjLinkProps {
  size?: 'sm' | 'md' | 'lg'
  iconPosition?: 'left' | 'right' | 'none'
  reset?: boolean
  external?: boolean
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { BjSvgIcon } from '../icons'

const props = withDefaults(defineProps<BjLinkProps>(), {
  size: 'md',
  iconPosition: 'none',
})

const classes = computed(() => [
  'bj-link',
  props.size !== 'md' && `bj-link--${props.size}`,
  props.iconPosition === 'left' && 'bj-link--icon-left',
  props.iconPosition === 'right' && 'bj-link--icon-right',
  props.reset && 'bj-link--reset',
  props.external && 'bj-link--external',
])
</script>

<template>
  <a
    :class="classes"
    :target="external ? '_blank' : undefined"
    :rel="external ? 'noopener noreferrer' : undefined"
    v-bind="$attrs"
  >
    <slot />
    <BjSvgIcon v-if="external" class="bj-link__external-icon" name="externalLinkLine" aria-hidden="true" />
  </a>
</template>
