// src/react/components/BjMarquee.tsx
import { useState, type ReactNode } from 'react'

import { BjSvgIcon } from '../icons'

export interface BjMarqueeProps {
  speed?: 'slow' | 'default' | 'fast'
  reverse?: boolean
  bordered?: boolean
  pausable?: boolean
  children?: ReactNode
  className?: string
}

export function BjMarquee({
  speed = 'default',
  reverse = false,
  bordered = false,
  pausable = true,
  children,
  className,
}: BjMarqueeProps) {
  const [paused, setPaused] = useState(false)

  function togglePause() {
    setPaused(p => !p)
  }

  return (
    <div
      className={[
        'bj-marquee',
        paused && 'bj-marquee--paused',
        reverse && 'bj-marquee--reverse',
        speed !== 'default' && `bj-marquee--${speed}`,
        bordered && 'bj-marquee--bordered',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      aria-live={paused ? 'polite' : 'off'}
    >
      <div className="bj-marquee__track">
        {children}
        {children}
      </div>
      {pausable ? (
        <button
          type="button"
          className="bj-marquee__pause"
          aria-label={paused ? 'Reprendre le défilement' : 'Mettre en pause le défilement'}
          onClick={togglePause}
        >
          <BjSvgIcon name={paused ? 'playLine' : 'pauseLine'} />
        </button>
      ) : null}
    </div>
  )
}

BjMarquee.displayName = 'BjMarquee'

// src/vue/components/BjMarquee.vue
<script lang="ts">
export interface BjMarqueeProps {
  speed?: 'slow' | 'default' | 'fast'
  reverse?: boolean
  bordered?: boolean
  pausable?: boolean
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { BjSvgIcon } from '../icons'

const props = withDefaults(defineProps<BjMarqueeProps>(), {
  speed: 'default',
  pausable: true,
})

const paused = ref(false)

const classes = computed(() => [
  'bj-marquee',
  paused.value && 'bj-marquee--paused',
  props.reverse && 'bj-marquee--reverse',
  props.speed !== 'default' && `bj-marquee--${props.speed}`,
  props.bordered && 'bj-marquee--bordered',
])

const pauseIconName = computed(() => (paused.value ? 'playLine' : 'pauseLine'))

function togglePause() {
  paused.value = !paused.value
}
</script>

<template>
  <div
    :class="classes"
    :aria-live="paused ? 'polite' : 'off'"
    @mouseenter="paused || (paused = false)"
    v-bind="$attrs"
  >
    <div class="bj-marquee__track">
      <slot />
      <slot />
    </div>
    <button
      v-if="pausable"
      type="button"
      class="bj-marquee__pause"
      :aria-label="paused ? 'Reprendre le défilement' : 'Mettre en pause le défilement'"
      @click="togglePause"
    >
      <BjSvgIcon :name="pauseIconName" />
    </button>
  </div>
</template>
