// src/react/components/BjModal.tsx
import { useEffect, useId, useRef, type ReactNode } from 'react'
import { createPortal } from 'react-dom'

import { BjSvgIcon } from '../icons'
import { useFocusTrap } from '../hooks/useFocusTrap'

export interface BjModalProps {
  open: boolean
  onClose: () => void
  size?: 'default' | 'sm' | 'lg' | 'full'
  title?: string
  closeLabel?: string
  children?: ReactNode
  footer?: ReactNode
  className?: string
}

export function BjModal({
  open,
  onClose,
  size = 'default',
  title,
  closeLabel = 'Fermer',
  children,
  footer,
  className,
}: BjModalProps) {
  const baseId = useId()
  const modalId = `bj-modal-${baseId.replace(/:/g, '')}`
  const titleId = `${modalId}-title`
  const dialogRef = useRef<HTMLDivElement>(null)

  useFocusTrap(dialogRef, open)

  useEffect(() => {
    if (open) document.body.classList.add('bj-modal-open')
    else document.body.classList.remove('bj-modal-open')
    return () => document.body.classList.remove('bj-modal-open')
  }, [open])

  useEffect(() => {
    if (!open) return
    const onEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', onEsc)
    return () => document.removeEventListener('keydown', onEsc)
  }, [open, onClose])

  if (!open) return null

  const node = (
    <div
      ref={dialogRef}
      id={modalId}
      className={['bj-modal', size !== 'default' && `bj-modal--${size}`, className]
        .filter(Boolean)
        .join(' ')}
      data-bj-expanded
      role="dialog"
      aria-modal="true"
      aria-labelledby={title ? titleId : undefined}
      style={{ display: 'flex' }}
    >
      <div className="bj-modal__overlay" role="presentation" onClick={onClose} />
      <div className="bj-modal__dialog">
        {title ? (
          <header className="bj-modal__header">
            <h2 id={titleId} className="bj-modal__title">
              {title}
            </h2>
            <button type="button" className="bj-modal__close" aria-label={closeLabel} onClick={onClose}>
              <BjSvgIcon name="closeLine" />
            </button>
          </header>
        ) : null}
        <div className="bj-modal__body">{children}</div>
        {footer ? <footer className="bj-modal__footer">{footer}</footer> : null}
      </div>
    </div>
  )

  return createPortal(node, document.body)
}

BjModal.displayName = 'BjModal'

// src/vue/components/BjModal.vue
<script lang="ts">
export interface BjModalProps {
  modelValue?: boolean
  size?: 'default' | 'sm' | 'lg' | 'full'
  title?: string
  id?: string
  closeLabel?: string
}
</script>

<script setup lang="ts">
import { computed, ref, watch, onMounted, onBeforeUnmount, nextTick } from 'vue'
import { BjSvgIcon } from '../icons'
import { useFocusTrap } from '../composables/useFocusTrap'

let modalUid = 0

const props = withDefaults(defineProps<BjModalProps>(), {
  modelValue: false,
  size: 'default',
  closeLabel: 'Fermer',
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

const modalRef = ref<HTMLElement>()
let previousFocus: HTMLElement | null = null

useFocusTrap(modalRef, () => props.modelValue)

const classes = computed(() => [
  'bj-modal',
  props.size !== 'default' && `bj-modal--${props.size}`,
])

const modalId = computed(() => props.id || `bj-modal-${++modalUid}`)
const titleId = computed(() => `${modalId.value}-title`)

function open() {
  previousFocus = document.activeElement as HTMLElement
  emit('update:modelValue', true)
  document.body.classList.add('bj-modal-open')
}

function close() {
  emit('update:modelValue', false)
  document.body.classList.remove('bj-modal-open')
  nextTick(() => previousFocus?.focus())
}

function onOverlayClick() {
  close()
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape' && props.modelValue) close()
}

watch(() => props.modelValue, (val) => {
  if (val) document.body.classList.add('bj-modal-open')
  else document.body.classList.remove('bj-modal-open')
})

onMounted(() => document.addEventListener('keydown', onKeydown))
onBeforeUnmount(() => {
  document.removeEventListener('keydown', onKeydown)
  document.body.classList.remove('bj-modal-open')
})

defineExpose({ open, close })
</script>

<template>
  <div
    v-if="modelValue"
    ref="modalRef"
    :id="modalId"
    :class="classes"
    data-bj-expanded
    role="dialog"
    aria-modal="true"
    :aria-labelledby="title ? titleId : undefined"
    style="display: flex"
  >
    <div class="bj-modal__overlay" @click="onOverlayClick" />
    <div class="bj-modal__dialog">
      <header v-if="title || $slots.header" class="bj-modal__header">
        <slot name="header">
          <h2 :id="titleId" class="bj-modal__title">{{ title }}</h2>
        </slot>
        <button type="button" class="bj-modal__close" :aria-label="closeLabel" @click="close">
          <BjSvgIcon name="closeLine" />
        </button>
      </header>
      <div class="bj-modal__body">
        <slot />
      </div>
      <footer v-if="$slots.footer" class="bj-modal__footer">
        <slot name="footer" :close="close" />
      </footer>
    </div>
  </div>
</template>
