// src/react/components/BjQuote.tsx
import type { HTMLAttributes, ReactNode } from 'react'

export interface BjQuoteProps extends Omit<HTMLAttributes<HTMLElement>, 'children'> {
  accent?: boolean
  text?: string
  author?: string
  source?: string
  image?: string
  children?: ReactNode
}

export function BjQuote({
  accent,
  text,
  author,
  source,
  image,
  className,
  children,
  ...rest
}: BjQuoteProps) {
  const cls = ['bj-quote', accent && 'bj-quote--accent', className].filter(Boolean).join(' ')

  return (
    <figure className={cls} {...rest}>
      {image ? <img className="bj-quote__image" src={image} alt="" /> : null}
      <blockquote className="bj-quote__text">{children ?? text}</blockquote>
      {author || source ? (
        <figcaption>
          {author ? <span className="bj-quote__author">{author}</span> : null}
          {source ? <span className="bj-quote__source">{source}</span> : null}
        </figcaption>
      ) : null}
    </figure>
  )
}
BjQuote.displayName = 'BjQuote'

// src/vue/components/BjQuote.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface BjQuoteProps {
  accent?: boolean
  text?: string
  author?: string
  source?: string
  image?: string
}

const props = defineProps<BjQuoteProps>()

const classes = computed(() => [
  'bj-quote',
  props.accent && 'bj-quote--accent',
])
</script>

<template>
  <figure :class="classes" v-bind="$attrs">
    <img v-if="image" class="bj-quote__image" :src="image" alt="" />
    <blockquote class="bj-quote__text">
      <slot>{{ text }}</slot>
    </blockquote>
    <figcaption v-if="author || source">
      <span v-if="author" class="bj-quote__author">{{ author }}</span>
      <span v-if="source" class="bj-quote__source">{{ source }}</span>
    </figcaption>
  </figure>
</template>
