// src/react/components/BjSidemenu.tsx
import type { ComponentPropsWithoutRef } from 'react'

export type BjSidemenuLink = {
  label: string
  to: string
  active?: boolean
  children?: BjSidemenuLink[]
}

export type BjSidemenuProps = {
  title?: string
  links: BjSidemenuLink[]
} & ComponentPropsWithoutRef<'nav'>

function SidemenuSublist({ links }: { links: BjSidemenuLink[] }) {
  return (
    <ul className="bj-sidemenu__sublist">
      {links.map((child) => (
        <li key={child.to} className="bj-sidemenu__item">
          <a
            className={['bj-sidemenu__link', child.active && 'bj-sidemenu__link--active']
              .filter(Boolean)
              .join(' ')}
            href={child.to}
            aria-current={child.active ? 'page' : undefined}
          >
            {child.label}
          </a>
        </li>
      ))}
    </ul>
  )
}

export function BjSidemenu({ title, links, className, ...rest }: BjSidemenuProps) {
  return (
    <nav
      className={['bj-sidemenu', className].filter(Boolean).join(' ')}
      aria-label="Menu latéral"
      {...rest}
    >
      {title ? <p className="bj-sidemenu__title">{title}</p> : null}
      <ul className="bj-sidemenu__list">
        {links.map((link) => (
          <li key={link.to} className="bj-sidemenu__item">
            <a
              className={['bj-sidemenu__link', link.active && 'bj-sidemenu__link--active']
                .filter(Boolean)
                .join(' ')}
              href={link.to}
              aria-current={link.active ? 'page' : undefined}
            >
              {link.label}
            </a>
            {link.children?.length ? <SidemenuSublist links={link.children} /> : null}
          </li>
        ))}
      </ul>
    </nav>
  )
}

BjSidemenu.displayName = 'BjSidemenu'

// src/vue/components/BjSidemenu.vue
<script setup lang="ts">
export interface SidemenuLink {
  label: string
  to: string
  active?: boolean
  children?: SidemenuLink[]
}

export interface BjSidemenuProps {
  title?: string
  links: SidemenuLink[]
}

defineProps<BjSidemenuProps>()
</script>

<template>
  <nav class="bj-sidemenu" aria-label="Menu latéral" v-bind="$attrs">
    <p v-if="title" class="bj-sidemenu__title">{{ title }}</p>
    <ul class="bj-sidemenu__list">
      <li v-for="link in links" :key="link.to" class="bj-sidemenu__item">
        <a
          class="bj-sidemenu__link"
          :class="{ 'bj-sidemenu__link--active': link.active }"
          :href="link.to"
          :aria-current="link.active ? 'page' : undefined"
        >
          {{ link.label }}
        </a>
        <ul v-if="link.children?.length" class="bj-sidemenu__sublist">
          <li v-for="child in link.children" :key="child.to" class="bj-sidemenu__item">
            <a
              class="bj-sidemenu__link"
              :class="{ 'bj-sidemenu__link--active': child.active }"
              :href="child.to"
            >
              {{ child.label }}
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</template>
