// src/react/components/BjStepper.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react'

export type BjStepperStep = {
  label: string
  done?: boolean
}

export type BjStepperProps = {
  title?: string
  steps: BjStepperStep[]
  current: number
  vertical?: boolean
  detail?: string
  ariaLabel?: string
  children?: ReactNode
} & ComponentPropsWithoutRef<'div'>

export function BjStepper({
  title,
  steps,
  current,
  vertical,
  detail,
  ariaLabel = 'Étapes',
  children,
  className,
  ...rest
}: BjStepperProps) {
  const cls = ['bj-stepper', vertical && 'bj-stepper--vertical', className].filter(Boolean).join(' ')

  return (
    <div className={cls} role="navigation" aria-label={ariaLabel} {...rest}>
      <div className="bj-stepper__header">
        {title ? <h2 className="bj-stepper__title">{title}</h2> : null}
        <div className="bj-stepper__steps" role="list">
          {steps.map((step, i) => (
            <div
              key={i}
              className={[
                'bj-stepper__step',
                i === current && 'bj-stepper__step--current',
                (step.done || i < current) && 'bj-stepper__step--done',
              ]
                .filter(Boolean)
                .join(' ')}
              role="listitem"
              aria-current={i === current ? 'step' : undefined}
            >
              {step.label}
            </div>
          ))}
        </div>
        {detail ? <p className="bj-stepper__detail">{detail}</p> : null}
      </div>
      {children}
    </div>
  )
}

BjStepper.displayName = 'BjStepper'

// src/vue/components/BjStepper.vue
<script lang="ts">
export interface StepperStep {
  label: string
  done?: boolean
}
export interface BjStepperProps {
  title?: string
  steps: StepperStep[]
  current: number
  vertical?: boolean
  detail?: string
  ariaLabel?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<BjStepperProps>(), {
  current: 0,
  ariaLabel: 'Étapes',
})

const classes = computed(() => [
  'bj-stepper',
  props.vertical && 'bj-stepper--vertical',
])
</script>

<template>
  <div :class="classes" role="navigation" :aria-label="ariaLabel" v-bind="$attrs">
    <div class="bj-stepper__header">
      <h2 v-if="title" class="bj-stepper__title">{{ title }}</h2>
      <div class="bj-stepper__steps" role="list">
        <div
          v-for="(step, i) in steps"
          :key="i"
          class="bj-stepper__step"
          :class="{
            'bj-stepper__step--current': i === current,
            'bj-stepper__step--done': step.done || i < current,
          }"
          role="listitem"
          :aria-current="i === current ? 'step' : undefined"
        >
          {{ step.label }}
        </div>
      </div>
      <p v-if="detail" class="bj-stepper__detail">{{ detail }}</p>
    </div>
    <slot />
  </div>
</template>
