// src/react/components/BjSummary.tsx
import type { ComponentPropsWithoutRef } from 'react'

export type BjSummaryLink = {
  label: string
  anchor: string
}

export type BjSummaryProps = {
  title?: string
  links: BjSummaryLink[]
} & ComponentPropsWithoutRef<'nav'>

export function BjSummary({ title = 'Sommaire', links, className, ...rest }: BjSummaryProps) {
  return (
    <nav
      className={['bj-summary', className].filter(Boolean).join(' ')}
      aria-label={title}
      {...rest}
    >
      <p className="bj-summary__title">{title}</p>
      <ul className="bj-summary__list">
        {links.map((link) => (
          <li key={link.anchor}>
            <a className="bj-summary__link" href={link.anchor}>
              {link.label}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  )
}

BjSummary.displayName = 'BjSummary'

// src/vue/components/BjSummary.vue
<script lang="ts">
export interface SummaryLink {
  label: string
  anchor: string
}
export interface BjSummaryProps {
  title?: string
  links: SummaryLink[]
}
</script>

<script setup lang="ts">

const props = withDefaults(defineProps<BjSummaryProps>(), {
  title: 'Sommaire',
})
</script>

<template>
  <nav class="bj-summary" :aria-label="title" v-bind="$attrs">
    <p class="bj-summary__title">{{ title }}</p>
    <ul class="bj-summary__list">
      <li v-for="link in links" :key="link.anchor">
        <a class="bj-summary__link" :href="link.anchor">{{ link.label }}</a>
      </li>
    </ul>
  </nav>
</template>
