// src/react/components/BjTag.tsx
import {
  forwardRef,
  type AnchorHTMLAttributes,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
  type MouseEvent,
  type ReactNode,
} from 'react'

import { BjSvgIcon } from '../icons'

export interface BjTagBaseProps {
  variant?: 'default' | 'action' | 'info' | 'success' | 'warning' | 'error'
  size?: 'sm' | 'md'
  dismissible?: boolean
  onDismiss?: () => void
  as?: 'span' | 'a' | 'button'
  children?: ReactNode
}

type BjTagAsSpan = BjTagBaseProps & { as?: 'span' } & Omit<
  HTMLAttributes<HTMLSpanElement>,
  keyof BjTagBaseProps
>
type BjTagAsAnchor = BjTagBaseProps & { as: 'a' } & Omit<
  AnchorHTMLAttributes<HTMLAnchorElement>,
  keyof BjTagBaseProps
>
type BjTagAsButton = BjTagBaseProps & { as: 'button' } & Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  keyof BjTagBaseProps
>

export type BjTagProps = BjTagAsSpan | BjTagAsAnchor | BjTagAsButton

export const BjTag = forwardRef<HTMLSpanElement | HTMLAnchorElement | HTMLButtonElement, BjTagProps>(
  (
    {
      variant = 'default',
      size = 'md',
      dismissible,
      onDismiss,
      as: Tag = 'span',
      className,
      children,
      ...rest
    },
    ref
  ) => {
    const cls = [
      'bj-tag',
      variant !== 'default' && `bj-tag--${variant}`,
      size === 'sm' && 'bj-tag--sm',
      dismissible && 'bj-tag--dismiss',
      className,
    ]
      .filter(Boolean)
      .join(' ')

    function handleDismissClick(e: MouseEvent<HTMLButtonElement>) {
      e.stopPropagation()
      onDismiss?.()
    }

    return (
      <Tag ref={ref as never} className={cls} {...(rest as Record<string, unknown>)}>
        {children}
        {dismissible ? (
          <button
            type="button"
            className="bj-tag__close"
            aria-label="Retirer"
            onClick={handleDismissClick}
          >
            <BjSvgIcon name="closeLine" />
          </button>
        ) : null}
      </Tag>
    )
  }
)
BjTag.displayName = 'BjTag'

// src/vue/components/BjTag.vue
<script lang="ts">
export interface BjTagProps {
  variant?: 'default' | 'action' | 'info' | 'success' | 'warning' | 'error'
  size?: 'sm' | 'md'
  dismissible?: boolean
  tag?: 'span' | 'a' | 'button'
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { BjSvgIcon } from '../icons'

const props = withDefaults(defineProps<BjTagProps>(), {
  variant: 'default',
  size: 'md',
  tag: 'span',
})

const emit = defineEmits<{ dismiss: [] }>()

const classes = computed(() => [
  'bj-tag',
  props.variant !== 'default' && `bj-tag--${props.variant}`,
  props.size === 'sm' && 'bj-tag--sm',
  props.dismissible && 'bj-tag--dismiss',
])
</script>

<template>
  <component :is="tag" :class="classes" v-bind="$attrs">
    <slot />
    <button
      v-if="dismissible"
      type="button"
      class="bj-tag__close"
      aria-label="Retirer"
      @click.stop="emit('dismiss')"
    >
      <BjSvgIcon name="closeLine" />
    </button>
  </component>
</template>
