// src/react/components/BjToggle.tsx
import { useId } from 'react'
import type * as React from 'react'

export interface BjToggleProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'size' | 'role' | 'id' | 'children'> {
  checked?: boolean
  onChange?: React.ChangeEventHandler<HTMLInputElement>
  label?: string
  hint?: string
  disabled?: boolean
  border?: boolean
  labelLeft?: boolean
  id?: string
  children?: React.ReactNode
}

export function BjToggle({
  checked = false,
  onChange,
  label,
  hint,
  disabled,
  border,
  labelLeft,
  id: idProp,
  className,
  children,
  ...rest
}: BjToggleProps) {
  const uid = useId()
  const toggleId = idProp ?? uid
  const hintId = `${toggleId}-hint`

  const describedBy = hint ? hintId : undefined

  const labelClass = ['bj-toggle', border && 'bj-toggle--border', labelLeft && 'bj-toggle--label-left', className].filter(Boolean).join(' ')

  return (
    <label className={labelClass} htmlFor={toggleId}>
      <input
        id={toggleId}
        type="checkbox"
        className="bj-toggle__input"
        role="switch"
        checked={checked}
        disabled={disabled}
        aria-checked={checked}
        aria-describedby={describedBy}
        onChange={onChange}
        {...rest}
      />
      <span className="bj-toggle__label">
        {children ?? label}
        {hint ? <span id={hintId} className="bj-toggle__hint">{hint}</span> : null}
      </span>
    </label>
  )
}

BjToggle.displayName = 'BjToggle'

// src/vue/components/BjToggle.vue
<script lang="ts">
export interface BjToggleProps {
  modelValue?: boolean
  label?: string
  hint?: string
  disabled?: boolean
  border?: boolean
  labelLeft?: boolean
  id?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

let uid = 0

const props = withDefaults(defineProps<BjToggleProps>(), {
  modelValue: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

const toggleId = props.id || `bj-toggle-${++uid}`
const hintId = `${toggleId}-hint`

const classes = computed(() => [
  'bj-toggle',
  props.border && 'bj-toggle--border',
  props.labelLeft && 'bj-toggle--label-left',
])

const describedBy = computed(() => {
  if (props.hint) return hintId
  return undefined
})

function onChange(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).checked)
}
</script>

<template>
  <label :class="classes" :for="toggleId">
    <input
      :id="toggleId"
      type="checkbox"
      class="bj-toggle__input"
      role="switch"
      :checked="modelValue"
      :disabled="disabled"
      :aria-checked="modelValue"
      :aria-describedby="describedBy"
      v-bind="$attrs"
      @change="onChange"
    />
    <span class="bj-toggle__label">
      <slot>{{ label }}</slot>
      <span v-if="hint" :id="hintId" class="bj-toggle__hint">{{ hint }}</span>
    </span>
  </label>
</template>
