// src/react/components/BjTreeview.tsx
import { useCallback, useState, type Dispatch, type SetStateAction } from 'react'

export type TreeNode = {
  id: string
  label: string
  icon?: string
  children?: TreeNode[]
  checked?: boolean
}

function collectChecked(nodes: TreeNode[]): string[] {
  const result: string[] = []
  for (const n of nodes) {
    if (n.checked) result.push(n.id)
    if (n.children?.length) result.push(...collectChecked(n.children))
  }
  return result
}

export interface BjTreeviewProps {
  nodes: TreeNode[]
  checkbox?: boolean
  compact?: boolean
  onCheck?: (id: string, checked: boolean) => void
  onToggle?: (id: string, expanded: boolean) => void
  className?: string
}

interface BjTreeviewBranchProps extends BjTreeviewProps {
  expanded: Set<string>
  checkedSet: Set<string>
  setExpanded: Dispatch<SetStateAction<Set<string>>>
  setCheckedSet: Dispatch<SetStateAction<Set<string>>>
}

function BjTreeviewBranch({
  nodes,
  checkbox = false,
  compact = false,
  onCheck,
  onToggle,
  className,
  expanded,
  checkedSet,
  setExpanded,
  setCheckedSet,
}: BjTreeviewBranchProps) {
  const toggleExpand = useCallback(
    (id: string) => {
      setExpanded(prev => {
        const next = new Set(prev)
        const wasExpanded = next.has(id)
        if (wasExpanded) next.delete(id)
        else next.add(id)
        onToggle?.(id, !wasExpanded)
        return next
      })
    },
    [onToggle, setExpanded],
  )

  const toggleCheck = useCallback(
    (id: string) => {
      setCheckedSet(prev => {
        const next = new Set(prev)
        const wasChecked = next.has(id)
        if (wasChecked) next.delete(id)
        else next.add(id)
        onCheck?.(id, !wasChecked)
        return next
      })
    },
    [onCheck, setCheckedSet],
  )

  const isExpanded = (id: string) => expanded.has(id)
  const isChecked = (id: string) => checkedSet.has(id)

  return (
    <ul
      className={[
        'bj-tree',
        compact && 'bj-tree--compact',
        checkbox && 'bj-tree--checkbox',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      role="tree"
    >
      {nodes.map(node => (
        <li key={node.id} className="bj-tree__item" role="treeitem">
          <div className="bj-tree__item-content">
            {node.children?.length ? (
              <button
                type="button"
                className="bj-tree__toggle"
                aria-expanded={isExpanded(node.id)}
                data-bj-tree-toggle
                onClick={() => toggleExpand(node.id)}
              >
                <i className="ri-arrow-right-s-line" aria-hidden="true" />
              </button>
            ) : (
              <span className="bj-tree__toggle-spacer" />
            )}
            {checkbox ? (
              <input
                type="checkbox"
                className="bj-tree__checkbox"
                checked={isChecked(node.id)}
                onChange={() => toggleCheck(node.id)}
              />
            ) : null}
            {node.icon ? <i className={['bj-tree__icon', node.icon].filter(Boolean).join(' ')} aria-hidden="true" /> : null}
            <span className="bj-tree__label">{node.label}</span>
          </div>
          {node.children?.length ? (
            <ul className="bj-tree__branch" hidden={!isExpanded(node.id)} role="group">
              <BjTreeviewBranch
                nodes={node.children}
                checkbox={checkbox}
                compact={compact}
                onCheck={onCheck}
                onToggle={onToggle}
                expanded={expanded}
                checkedSet={checkedSet}
                setExpanded={setExpanded}
                setCheckedSet={setCheckedSet}
              />
            </ul>
          ) : null}
        </li>
      ))}
    </ul>
  )
}

export function BjTreeview({
  nodes,
  checkbox = false,
  compact = false,
  onCheck,
  onToggle,
  className,
}: BjTreeviewProps) {
  const [expanded, setExpanded] = useState<Set<string>>(() => new Set())
  const [checkedSet, setCheckedSet] = useState<Set<string>>(() => new Set(collectChecked(nodes)))

  return (
    <BjTreeviewBranch
      nodes={nodes}
      checkbox={checkbox}
      compact={compact}
      onCheck={onCheck}
      onToggle={onToggle}
      className={className}
      expanded={expanded}
      checkedSet={checkedSet}
      setExpanded={setExpanded}
      setCheckedSet={setCheckedSet}
    />
  )
}

BjTreeview.displayName = 'BjTreeview'

// src/vue/components/BjTreeview.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = withDefaults(defineProps<BjTreeviewProps>(), {
  checkbox: false,
  compact: false,
})

const emit = defineEmits<{
  check: [id: string, checked: boolean]
  toggle: [id: string, expanded: boolean]
}>()

const expanded = ref<Set<string>>(new Set())
const checked = ref<Set<string>>(new Set(
  collectChecked(props.nodes)
))

function collectChecked(nodes: TreeNode[]): string[] {
  const result: string[] = []
  for (const n of nodes) {
    if (n.checked) result.push(n.id)
    if (n.children) result.push(...collectChecked(n.children))
  }
  return result
}

function toggleExpand(id: string) {
  const next = new Set(expanded.value)
  const isExpanded = next.has(id)
  if (isExpanded) next.delete(id)
  else next.add(id)
  expanded.value = next
  emit('toggle', id, !isExpanded)
}

function toggleCheck(id: string) {
  const next = new Set(checked.value)
  const isChecked = next.has(id)
  if (isChecked) next.delete(id)
  else next.add(id)
  checked.value = next
  emit('check', id, !isChecked)
}

function isExpanded(id: string) { return expanded.value.has(id) }
function isChecked(id: string) { return checked.value.has(id) }
</script>

<template>
  <ul
    class="bj-tree"
    :class="{
      'bj-tree--compact': compact,
      'bj-tree--checkbox': checkbox,
    }"
    role="tree"
    v-bind="$attrs"
  >
    <li v-for="node in nodes" :key="node.id" class="bj-tree__item" role="treeitem">
      <div class="bj-tree__item-content">
        <button
          v-if="node.children?.length"
          type="button"
          class="bj-tree__toggle"
          :aria-expanded="String(isExpanded(node.id))"
          data-bj-tree-toggle
          @click="toggleExpand(node.id)"
        >
          <i class="ri-arrow-right-s-line" aria-hidden="true" />
        </button>
        <span v-else class="bj-tree__toggle-spacer" />
        <input
          v-if="checkbox"
          type="checkbox"
          class="bj-tree__checkbox"
          :checked="isChecked(node.id)"
          @change="toggleCheck(node.id)"
        />
        <i v-if="node.icon" class="bj-tree__icon" :class="node.icon" aria-hidden="true" />
        <span class="bj-tree__label">{{ node.label }}</span>
      </div>
      <ul
        v-if="node.children?.length"
        class="bj-tree__branch"
        :hidden="!isExpanded(node.id)"
        role="group"
      >
        <BjTreeview
          :nodes="node.children"
          :checkbox="checkbox"
          :compact="compact"
          @check="(id, val) => emit('check', id, val)"
          @toggle="(id, val) => emit('toggle', id, val)"
        />
      </ul>
    </li>
  </ul>
</template>

<script lang="ts">
export interface TreeNode {
  id: string
  label: string
  icon?: string
  children?: TreeNode[]
  checked?: boolean
}
export interface BjTreeviewProps {
  nodes: TreeNode[]
  checkbox?: boolean
  compact?: boolean
}

export default { name: 'BjTreeview' }
</script>
