// src/react/components/BjUpload.tsx
import { useId, useRef, useState } from 'react'
import type * as React from 'react'

import { BjSvgIcon, remixClassToIconName } from '../icons'

export interface BjUploadProps {
  label?: string
  hint?: string
  accept?: string
  multiple?: boolean
  error?: boolean
  message?: string
  text?: string
  icon?: string
  removeLabel?: string
  onChange?: (files: FileList | null) => void
  className?: string
}

export function BjUpload({
  label,
  hint,
  accept,
  multiple,
  error,
  message,
  text = 'Glissez un fichier ou cliquez pour parcourir',
  icon = 'upload2Line',
  removeLabel = 'Retirer',
  onChange,
  className,
}: BjUploadProps) {
  const uid = useId()
  const uploadId = `bj-upload-${uid.replace(/:/g, '')}`
  const hintId = `${uploadId}-hint`
  const messageId = `${uploadId}-msg`
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [files, setFiles] = useState<File[]>([])
  const [dragging, setDragging] = useState(false)

  const describedBy =
    [hint && hintId, message && messageId].filter(Boolean).join(' ') || undefined

  const groupClass = ['bj-upload-group', error && 'bj-upload-group--error', className].filter(Boolean).join(' ')
  const uploadClass = ['bj-upload', dragging && 'bj-upload--drag-over'].filter(Boolean).join(' ')

  function handleFiles(fl: FileList | null) {
    if (!fl?.length) return
    setFiles(Array.from(fl))
    onChange?.(fl)
  }

  function onClick() {
    fileInputRef.current?.click()
  }

  function onDrop(e: React.DragEvent) {
    e.preventDefault()
    setDragging(false)
    handleFiles(e.dataTransfer?.files ?? null)
  }

  function removeFile(index: number) {
    setFiles((prev) => prev.filter((_, i) => i !== index))
    if (fileInputRef.current) fileInputRef.current.value = ''
  }

  return (
    <div className={groupClass}>
      {label ? (
        <label className="bj-label" htmlFor={uploadId}>
          {label}
        </label>
      ) : null}
      {hint ? <span id={hintId} className="bj-hint">{hint}</span> : null}
      <div
        className={uploadClass}
        role="button"
        tabIndex={0}
        aria-label={text}
        aria-describedby={describedBy}
        onClick={onClick}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            onClick()
          }
        }}
        onDragOver={(e) => {
          e.preventDefault()
          setDragging(true)
        }}
        onDragLeave={() => setDragging(false)}
        onDrop={onDrop}
      >
        <span className="bj-upload__icon" aria-hidden="true">
          <BjSvgIcon name={remixClassToIconName(icon)} />
        </span>
        <span className="bj-upload__text">{text}</span>
        <input
          ref={fileInputRef}
          id={uploadId}
          type="file"
          accept={accept}
          multiple={multiple}
          onChange={(e) => handleFiles(e.target.files)}
        />
      </div>
      {message ? (
        <p
          id={messageId}
          className={['bj-message', error ? 'bj-message--error' : 'bj-message--info'].filter(Boolean).join(' ')}
          role={error ? 'alert' : 'status'}
        >
          {message}
        </p>
      ) : null}
      {files.map((file, i) => (
        <div key={`${file.name}-${i}`} className="bj-upload__file">
          <BjSvgIcon name="fileLine" />
          {file.name}
          <button
            type="button"
            className="bj-upload__file-remove"
            onClick={() => removeFile(i)}
            aria-label={`${removeLabel} ${file.name}`}
          >
            <BjSvgIcon name="closeLine" />
          </button>
        </div>
      ))}
    </div>
  )
}

BjUpload.displayName = 'BjUpload'

// src/vue/components/BjUpload.vue
<script lang="ts">
export interface BjUploadProps {
  label?: string
  hint?: string
  accept?: string
  multiple?: boolean
  error?: boolean
  message?: string
  text?: string
  icon?: string
  id?: string
  removeLabel?: string
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { BjSvgIcon } from '../icons'

let uid = 0

function riKebabToCamel(s: string): string {
  return s.split('-').map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('')
}

function resolveIconName(icon: string): string {
  if (icon.startsWith('ri-')) return riKebabToCamel(icon.replace(/^ri-/, ''))
  return icon
}

const props = withDefaults(defineProps<BjUploadProps>(), {
  text: 'Glissez un fichier ou cliquez pour parcourir',
  icon: 'upload2Line',
  removeLabel: 'Retirer',
})

const iconName = computed(() => resolveIconName(props.icon))

const emit = defineEmits<{
  change: [files: FileList | null]
}>()

const fileInput = ref<HTMLInputElement>()
const files = ref<File[]>([])
const dragging = ref(false)

const groupClasses = computed(() => [
  'bj-upload-group',
  props.error && 'bj-upload-group--error',
])

const uploadClasses = computed(() => [
  'bj-upload',
  dragging.value && 'bj-upload--drag-over',
])

const uploadId = props.id || `bj-upload-${++uid}`
const hintId = `${uploadId}-hint`
const messageId = `${uploadId}-msg`

const describedBy = computed(() => {
  const ids: string[] = []
  if (props.hint) ids.push(hintId)
  if (props.message) ids.push(messageId)
  return ids.length ? ids.join(' ') : undefined
})

function handleFiles(fl: FileList | null) {
  if (!fl) return
  files.value = Array.from(fl)
  emit('change', fl)
}

function onClick() {
  fileInput.value?.click()
}

function onDrop(e: DragEvent) {
  dragging.value = false
  handleFiles(e.dataTransfer?.files ?? null)
}

function removeFile(index: number) {
  files.value.splice(index, 1)
  if (fileInput.value) fileInput.value.value = ''
}
</script>

<template>
  <div :class="groupClasses">
    <label v-if="label" class="bj-label" :for="uploadId">{{ label }}</label>
    <span v-if="hint" :id="hintId" class="bj-hint">{{ hint }}</span>
    <div
      :class="uploadClasses"
      role="button"
      tabindex="0"
      :aria-label="text"
      :aria-describedby="describedBy"
      @click="onClick"
      @keydown.enter="onClick"
      @keydown.space.prevent="onClick"
      @dragover.prevent="dragging = true"
      @dragleave="dragging = false"
      @drop.prevent="onDrop"
    >
      <BjSvgIcon class="bj-upload__icon" :name="iconName" />
      <span class="bj-upload__text">{{ text }}</span>
      <span v-if="$slots.uploadHint" class="bj-upload__hint"><slot name="uploadHint" /></span>
      <input
        ref="fileInput"
        :id="uploadId"
        type="file"
        :accept="accept"
        :multiple="multiple"
        @change="handleFiles(($event.target as HTMLInputElement).files)"
      />
    </div>
    <p
      v-if="message"
      :id="messageId"
      class="bj-message"
      :class="error ? 'bj-message--error' : 'bj-message--info'"
      :role="error ? 'alert' : 'status'"
    >
      {{ message }}
    </p>
    <div v-for="(file, i) in files" :key="i" class="bj-upload__file">
      <BjSvgIcon name="fileLine" />
      {{ file.name }}
      <button type="button" class="bj-upload__file-remove" @click="removeFile(i)" :aria-label="`${removeLabel} ${file.name}`">
        <BjSvgIcon name="closeLine" />
      </button>
    </div>
  </div>
</template>
