// src/vue/components/BjAccordionItem.vue
<script lang="ts">
export interface BjAccordionItemProps {
  id: string
  title: string
}
</script>

<script setup lang="ts">
import { computed, inject } from 'vue'
import { AccordionKey } from '../composables/useAccordion'

const props = defineProps<BjAccordionItemProps>()

const ctx = inject(AccordionKey)
if (!ctx) throw new Error('BjAccordionItem must be inside BjAccordion')

const isOpen = computed(() => ctx.openItems.value.has(props.id))
const panelId = computed(() => `accordion-panel-${props.id}`)
const btnId = computed(() => `accordion-btn-${props.id}`)

function toggle() {
  ctx.toggle(props.id)
}
</script>

<template>
  <div class="bj-accordion" :class="{ 'bj-accordion--expanded': isOpen }">
    <button
      :id="btnId"
      type="button"
      class="bj-accordion__btn"
      :aria-expanded="String(isOpen)"
      :aria-controls="panelId"
      @click="toggle"
    >
      {{ title }}
    </button>
    <div
      :id="panelId"
      class="bj-accordion__body"
      :data-bj-expanded="isOpen ? '' : undefined"
      role="region"
      :aria-labelledby="btnId"
    >
      <slot />
    </div>
  </div>
</template>

// src/react/components/BjAccordionItem.tsx
import { useContext, useId, type ReactNode } from 'react'
import { AccordionContext } from './BjAccordion'

export interface BjAccordionItemProps {
  id: string
  title: string
  children?: ReactNode
  className?: string
}

export function BjAccordionItem({ id, title, children, className }: BjAccordionItemProps) {
  const ctx = useContext(AccordionContext)
  if (!ctx) throw new Error('BjAccordionItem must be inside BjAccordion')

  const isOpen = ctx.openItems.has(id)
  const uid = useId()
  const panelId = `accordion-panel-${id}-${uid.replace(/:/g, '')}`
  const btnId = `accordion-btn-${id}-${uid.replace(/:/g, '')}`

  return (
    <div
      className={['bj-accordion', isOpen && 'bj-accordion--expanded', className]
        .filter(Boolean)
        .join(' ')}
    >
      <button
        id={btnId}
        type="button"
        className="bj-accordion__btn"
        aria-expanded={isOpen}
        aria-controls={panelId}
        onClick={() => ctx.toggle(id)}
      >
        {title}
      </button>
      <div
        id={panelId}
        className="bj-accordion__body"
        data-bj-expanded={isOpen ? '' : undefined}
        role="region"
        aria-labelledby={btnId}
      >
        {children}
      </div>
    </div>
  )
}

BjAccordionItem.displayName = 'BjAccordionItem'
