// src/vue/components/BjAlert.vue
<script lang="ts">
export interface BjAlertProps {
  variant?: 'info' | 'success' | 'warning' | 'error'
  size?: 'sm' | 'md'
  closable?: boolean
  title?: string
  closeLabel?: string
  role?: 'alert' | 'status'
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { BjSvgIcon } from '../icons'

const props = withDefaults(defineProps<BjAlertProps>(), {
  variant: 'info',
  size: 'md',
  closeLabel: 'Fermer',
})

const emit = defineEmits<{ close: [] }>()

const visible = ref(true)

const classes = computed(() => [
  'bj-alert',
  props.variant !== 'info' && `bj-alert--${props.variant}`,
  props.size === 'sm' && 'bj-alert--sm',
])

const effectiveRole = computed(() => {
  if (props.role) return props.role
  return props.variant === 'error' || props.variant === 'warning' ? 'alert' : 'status'
})

const iconMap: Record<'info' | 'success' | 'warning' | 'error', string> = {
  info: 'informationLine',
  success: 'checkboxCircleLine',
  warning: 'alertLine',
  error: 'errorWarningLine',
}

function close() {
  visible.value = false
  emit('close')
}
</script>

<template>
  <div v-if="visible" :class="classes" :role="effectiveRole" v-bind="$attrs">
    <span class="bj-alert__icon" aria-hidden="true"><BjSvgIcon :name="iconMap[variant]" /></span>
    <div class="bj-alert__body">
      <p v-if="title" class="bj-alert__title">{{ title }}</p>
      <div class="bj-alert__text">
        <slot />
      </div>
    </div>
    <button
      v-if="closable"
      type="button"
      class="bj-alert__close"
      :aria-label="closeLabel"
      @click="close"
    >
      <BjSvgIcon name="closeLine" />
    </button>
  </div>
</template>

// src/react/components/BjAlert.tsx
import { useState, type HTMLAttributes, type ReactNode } from 'react'
import { BjSvgIcon } from '../icons'

export interface BjAlertProps extends Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'title' | 'role'> {
  variant?: 'info' | 'success' | 'warning' | 'error'
  size?: 'sm' | 'md'
  closable?: boolean
  closeLabel?: string
  title?: string
  role?: 'alert' | 'status'
  onClose?: () => void
  children?: ReactNode
}

const iconMap: Record<NonNullable<BjAlertProps['variant']>, string> = {
  info: 'informationLine',
  success: 'checkboxCircleLine',
  warning: 'alertLine',
  error: 'errorWarningLine',
}

export function BjAlert({
  variant = 'info',
  size = 'md',
  closable,
  closeLabel = 'Fermer',
  title,
  role: roleProp,
  onClose,
  className,
  children,
  ...rest
}: BjAlertProps) {
  const [visible, setVisible] = useState(true)

  const effectiveRole = roleProp ?? (variant === 'error' || variant === 'warning' ? 'alert' : 'status')

  const cls = [
    'bj-alert',
    variant !== 'info' && `bj-alert--${variant}`,
    size === 'sm' && 'bj-alert--sm',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  function close() {
    setVisible(false)
    onClose?.()
  }

  if (!visible) return null

  return (
    <div className={cls} role={effectiveRole} {...rest}>
      <span className="bj-alert__icon" aria-hidden="true">
        <BjSvgIcon name={iconMap[variant]} />
      </span>
      <div className="bj-alert__body">
        {title ? <p className="bj-alert__title">{title}</p> : null}
        <div className="bj-alert__text">{children}</div>
      </div>
      {closable ? (
        <button type="button" className="bj-alert__close" aria-label={closeLabel} onClick={close}>
          <BjSvgIcon name="closeLine" />
        </button>
      ) : null}
    </div>
  )
}
BjAlert.displayName = 'BjAlert'
