// src/vue/components/BjCallout.vue
<script lang="ts">
export interface BjCalloutProps {
  color?: 'default' | 'green' | 'yellow' | 'red'
  icon?: string
  title?: string
  role?: 'alert' | 'status' | 'note'
}
</script>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<BjCalloutProps>(), {
  color: 'default',
})

const classes = computed(() => [
  'bj-callout',
  props.color !== 'default' && `bj-callout--${props.color}`,
])

const effectiveRole = computed(() => {
  if (props.role === 'note') return undefined
  return props.role || undefined
})
</script>

<template>
  <div :class="classes" :role="effectiveRole" v-bind="$attrs">
    <i v-if="icon" class="bj-callout__icon" :class="icon" aria-hidden="true" />
    <p v-if="title" class="bj-callout__title">{{ title }}</p>
    <div class="bj-callout__text">
      <slot />
    </div>
    <div v-if="$slots.action" class="bj-callout__btn">
      <slot name="action" />
    </div>
  </div>
</template>

// src/react/components/BjCallout.tsx
import type { HTMLAttributes, ReactNode } from 'react'

export interface BjCalloutProps extends Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'title' | 'role'> {
  color?: 'default' | 'green' | 'yellow' | 'red'
  icon?: string
  title?: string
  action?: ReactNode
  role?: 'alert' | 'status' | 'note'
  children?: ReactNode
}

export function BjCallout({
  color = 'default',
  icon,
  title,
  action,
  role: roleProp,
  className,
  children,
  ...rest
}: BjCalloutProps) {
  const effectiveRole = roleProp === 'note' ? undefined : roleProp

  const cls = [
    'bj-callout',
    color !== 'default' && `bj-callout--${color}`,
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={cls} role={effectiveRole} {...rest}>
      {icon ? <i className={`bj-callout__icon ${icon}`} aria-hidden="true" /> : null}
      {title ? <p className="bj-callout__title">{title}</p> : null}
      <div className="bj-callout__text">{children}</div>
      {action ? <div className="bj-callout__btn">{action}</div> : null}
    </div>
  )
}
BjCallout.displayName = 'BjCallout'
