// src/vue/components/BjCardImg.vue
<script lang="ts">
export interface BjCardImgProps {
  background?: string
  label?: string
  decorative?: boolean
}
</script>

<script setup lang="ts">

const props = withDefaults(defineProps<BjCardImgProps>(), {
  label: '',
})
</script>

<template>
  <div
    class="bj-card__img"
    :style="background ? { background } : undefined"
    :role="decorative ? undefined : 'img'"
    :aria-label="decorative ? undefined : label"
    :aria-hidden="decorative || undefined"
  >
    <slot />
  </div>
</template>

// src/react/components/BjCardImg.tsx
import type { CSSProperties, HTMLAttributes, ReactNode } from 'react'

export interface BjCardImgProps extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  background?: string
  label?: string
  decorative?: boolean
  children?: ReactNode
}

export function BjCardImg({
  background,
  label = '',
  decorative,
  className,
  children,
  style,
  ...rest
}: BjCardImgProps) {
  const cls = ['bj-card__img', className].filter(Boolean).join(' ')
  const mergedStyle: CSSProperties | undefined =
    background || style
      ? { ...(style ?? {}), ...(background ? { background } : {}) }
      : style

  return (
    <div
      className={cls}
      style={mergedStyle}
      role={decorative ? undefined : 'img'}
      aria-label={decorative ? undefined : label || undefined}
      aria-hidden={decorative || undefined}
      {...rest}
    >
      {children}
    </div>
  )
}
BjCardImg.displayName = 'BjCardImg'
