// src/vue/components/BjChatBubble.vue
<script lang="ts">
export interface BjChatBubbleProps {
  variant?: 'sent' | 'received' | 'system'
  avatar?: string
  sender?: string
  time?: string
  status?: 'sending' | 'sent' | 'read' | 'error'
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { BjSvgIcon } from '../icons'

const props = withDefaults(defineProps<BjChatBubbleProps>(), {
  variant: 'received',
})

const classes = computed(() => [
  'bj-chat-bubble',
  `bj-chat-bubble--${props.variant}`,
  props.status === 'error' && 'bj-chat-bubble--error',
])

const ariaLabel = computed(() => {
  const parts: string[] = []
  if (props.sender) parts.push(`Message de ${props.sender}`)
  if (props.time) parts.push(`à ${props.time}`)
  return parts.length ? parts.join(' ') : undefined
})

const statusIcon = computed(() => {
  switch (props.status) {
    case 'sending': return 'timeLine'
    case 'sent': return 'checkLine'
    case 'read': return 'checkDoubleLine'
    case 'error': return 'errorWarningLine'
    default: return null
  }
})
</script>

<template>
  <div
    :class="classes"
    role="listitem"
    :aria-label="ariaLabel"
    v-bind="$attrs"
  >
    <div v-if="avatar && variant !== 'system'" class="bj-chat-bubble__avatar">
      <img :src="avatar" :alt="sender || ''" />
    </div>
    <div class="bj-chat-bubble__content">
      <span v-if="sender && variant !== 'system'" class="bj-chat-bubble__sender">{{ sender }}</span>
      <div class="bj-chat-bubble__text">
        <slot />
      </div>
      <div v-if="time || status" class="bj-chat-bubble__meta">
        <span v-if="time" class="bj-chat-bubble__time">{{ time }}</span>
        <span v-if="statusIcon" :class="['bj-chat-bubble__status', `bj-chat-bubble__status--${status}`]">
          <BjSvgIcon :name="statusIcon" />
        </span>
      </div>
    </div>
  </div>
</template>

// src/react/components/BjChatBubble.tsx
import { type ReactNode } from 'react'
import { BjSvgIcon } from '../icons'

export interface BjChatBubbleProps {
  variant?: 'sent' | 'received' | 'system'
  avatar?: string
  sender?: string
  time?: string
  status?: 'sending' | 'sent' | 'read' | 'error'
  children?: ReactNode
  className?: string
}

const STATUS_ICONS: Record<NonNullable<BjChatBubbleProps['status']>, string> = {
  sending: 'timeLine',
  sent: 'checkLine',
  read: 'checkDoubleLine',
  error: 'errorWarningLine',
}

export function BjChatBubble({
  variant = 'received',
  avatar,
  sender,
  time,
  status,
  children,
  className,
}: BjChatBubbleProps) {
  const cls = [
    'bj-chat-bubble',
    `bj-chat-bubble--${variant}`,
    status === 'error' && 'bj-chat-bubble--error',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  const labelParts: string[] = []
  if (sender) labelParts.push(`Message de ${sender}`)
  if (time) labelParts.push(`à ${time}`)
  const ariaLabel = labelParts.length ? labelParts.join(' ') : undefined

  return (
    <div className={cls} role="listitem" aria-label={ariaLabel}>
      {avatar && variant !== 'system' ? (
        <div className="bj-chat-bubble__avatar">
          <img src={avatar} alt={sender || ''} />
        </div>
      ) : null}
      <div className="bj-chat-bubble__content">
        {sender && variant !== 'system' ? (
          <span className="bj-chat-bubble__sender">{sender}</span>
        ) : null}
        <div className="bj-chat-bubble__text">{children}</div>
        {time || status ? (
          <div className="bj-chat-bubble__meta">
            {time ? <span className="bj-chat-bubble__time">{time}</span> : null}
            {status && STATUS_ICONS[status] ? (
              <span className={`bj-chat-bubble__status bj-chat-bubble__status--${status}`}>
                <BjSvgIcon name={STATUS_ICONS[status]} />
              </span>
            ) : null}
          </div>
        ) : null}
      </div>
    </div>
  )
}

BjChatBubble.displayName = 'BjChatBubble'
