// src/vue/components/BjDashboardSidebar.vue
<script lang="ts">
export interface DashboardSidebarLink {
  label: string
  to: string
  icon?: string
  active?: boolean
  children?: DashboardSidebarLink[]
}

export interface DashboardSidebarSection {
  title?: string
  links: DashboardSidebarLink[]
}

export interface BjDashboardSidebarProps {
  brandText?: string
  brandImg?: string
  brandHref?: string
  sections?: DashboardSidebarSection[]
  compact?: boolean
}
</script>

<script setup lang="ts">
import { ref } from 'vue'

const props = withDefaults(defineProps<BjDashboardSidebarProps>(), {
  sections: () => [],
  compact: false,
})

const expanded = ref<Set<string>>(new Set())

function toggle(key: string) {
  const next = new Set(expanded.value)
  if (next.has(key)) next.delete(key)
  else next.add(key)
  expanded.value = next
}
</script>

<template>
  <aside
    class="bj-dashboard-sidebar"
    :class="{ 'bj-dashboard-sidebar--compact': compact }"
    v-bind="$attrs"
  >
    <component
      :is="brandHref ? 'a' : 'div'"
      v-if="brandImg || brandText"
      class="bj-dashboard-sidebar__brand"
      :href="brandHref || undefined"
    >
      <img v-if="brandImg" :src="brandImg" alt="" class="bj-dashboard-sidebar__brand-img" />
      <span v-if="brandText" class="bj-dashboard-sidebar__brand-text">{{ brandText }}</span>
    </component>

    <nav class="bj-dashboard-sidebar__nav" aria-label="Dashboard">
      <div v-for="(section, si) in sections" :key="si" class="bj-dashboard-sidebar__section">
        <p v-if="section.title" class="bj-dashboard-sidebar__section-title">{{ section.title }}</p>
        <ul class="bj-dashboard-sidebar__list">
          <li v-for="link in section.links" :key="link.to" class="bj-dashboard-sidebar__item">
            <template v-if="link.children?.length">
              <button
                type="button"
                class="bj-dashboard-sidebar__btn"
                :aria-expanded="expanded.has(link.to)"
                @click="toggle(link.to)"
              >
                <i v-if="link.icon" :class="link.icon" class="bj-dashboard-sidebar__link-icon" aria-hidden="true" />
                <span class="bj-dashboard-sidebar__link-label">{{ link.label }}</span>
              </button>
              <ul v-if="expanded.has(link.to)" class="bj-dashboard-sidebar__sublist">
                <li v-for="child in link.children" :key="child.to" class="bj-dashboard-sidebar__item">
                  <a
                    class="bj-dashboard-sidebar__link"
                    :class="{ 'bj-dashboard-sidebar__link--active': child.active }"
                    :href="child.to"
                    :aria-current="child.active ? 'page' : undefined"
                  >
                    <i v-if="child.icon" :class="child.icon" class="bj-dashboard-sidebar__link-icon" aria-hidden="true" />
                    <span class="bj-dashboard-sidebar__link-label">{{ child.label }}</span>
                  </a>
                </li>
              </ul>
            </template>
            <a
              v-else
              class="bj-dashboard-sidebar__link"
              :class="{ 'bj-dashboard-sidebar__link--active': link.active }"
              :href="link.to"
              :aria-current="link.active ? 'page' : undefined"
            >
              <i v-if="link.icon" :class="link.icon" class="bj-dashboard-sidebar__link-icon" aria-hidden="true" />
              <span class="bj-dashboard-sidebar__link-label">{{ link.label }}</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <div v-if="$slots.footer" class="bj-dashboard-sidebar__footer">
      <slot name="footer" />
    </div>
  </aside>
</template>

// src/react/components/BjDashboardSidebar.tsx
import { useState, type ComponentPropsWithoutRef, type ReactNode } from 'react'

export type BjDashboardSidebarLink = {
  label: string
  to: string
  icon?: string
  active?: boolean
  children?: BjDashboardSidebarLink[]
}

export type BjDashboardSidebarSection = {
  title?: string
  links: BjDashboardSidebarLink[]
}

export type BjDashboardSidebarProps = {
  brandText?: string
  brandImg?: string
  brandHref?: string
  sections?: BjDashboardSidebarSection[]
  compact?: boolean
  footer?: ReactNode
} & Omit<ComponentPropsWithoutRef<'aside'>, 'children'>

function SidebarLink({ link }: { link: BjDashboardSidebarLink }) {
  return (
    <a
      className={['bj-dashboard-sidebar__link', link.active && 'bj-dashboard-sidebar__link--active']
        .filter(Boolean)
        .join(' ')}
      href={link.to}
      aria-current={link.active ? 'page' : undefined}
    >
      {link.icon ? <i className={`${link.icon} bj-dashboard-sidebar__link-icon`} aria-hidden="true" /> : null}
      <span className="bj-dashboard-sidebar__link-label">{link.label}</span>
    </a>
  )
}

function CollapsibleItem({ link }: { link: BjDashboardSidebarLink }) {
  const [open, setOpen] = useState(false)

  return (
    <>
      <button
        type="button"
        className="bj-dashboard-sidebar__btn"
        aria-expanded={open}
        onClick={() => setOpen((v) => !v)}
      >
        {link.icon ? <i className={`${link.icon} bj-dashboard-sidebar__link-icon`} aria-hidden="true" /> : null}
        <span className="bj-dashboard-sidebar__link-label">{link.label}</span>
      </button>
      {open && link.children ? (
        <ul className="bj-dashboard-sidebar__sublist">
          {link.children.map((child) => (
            <li key={child.to} className="bj-dashboard-sidebar__item">
              <SidebarLink link={child} />
            </li>
          ))}
        </ul>
      ) : null}
    </>
  )
}

export function BjDashboardSidebar({
  brandText,
  brandImg,
  brandHref,
  sections = [],
  compact = false,
  footer,
  className,
  ...rest
}: BjDashboardSidebarProps) {
  const cls = ['bj-dashboard-sidebar', compact && 'bj-dashboard-sidebar--compact', className]
    .filter(Boolean)
    .join(' ')

  const BrandTag = brandHref ? 'a' : 'div'

  return (
    <aside className={cls} {...rest}>
      {brandImg || brandText ? (
        <BrandTag className="bj-dashboard-sidebar__brand" href={brandHref || undefined}>
          {brandImg ? <img src={brandImg} alt="" className="bj-dashboard-sidebar__brand-img" /> : null}
          {brandText ? <span className="bj-dashboard-sidebar__brand-text">{brandText}</span> : null}
        </BrandTag>
      ) : null}

      <nav className="bj-dashboard-sidebar__nav" aria-label="Dashboard">
        {sections.map((section, si) => (
          <div key={si} className="bj-dashboard-sidebar__section">
            {section.title ? <p className="bj-dashboard-sidebar__section-title">{section.title}</p> : null}
            <ul className="bj-dashboard-sidebar__list">
              {section.links.map((link) => (
                <li key={link.to} className="bj-dashboard-sidebar__item">
                  {link.children?.length ? <CollapsibleItem link={link} /> : <SidebarLink link={link} />}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </nav>

      {footer ? <div className="bj-dashboard-sidebar__footer">{footer}</div> : null}
    </aside>
  )
}

BjDashboardSidebar.displayName = 'BjDashboardSidebar'
