// src/vue/components/BjDrawer.vue
<script lang="ts">
export interface BjDrawerProps {
  modelValue?: boolean
  position?: 'left' | 'right'
  size?: 'default' | 'sm' | 'lg' | 'full'
  title?: string
  id?: string
  closeLabel?: string
}
</script>

<script setup lang="ts">
import { computed, ref, watch, onMounted, onBeforeUnmount, nextTick } from 'vue'
import { BjSvgIcon } from '../icons'
import { useFocusTrap } from '../composables/useFocusTrap'

let drawerUid = 0

const props = withDefaults(defineProps<BjDrawerProps>(), {
  modelValue: false,
  position: 'left',
  size: 'default',
  closeLabel: 'Fermer',
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

const drawerRef = ref<HTMLElement>()
let previousFocus: HTMLElement | null = null

useFocusTrap(drawerRef, () => props.modelValue)

const classes = computed(() => [
  'bj-drawer',
  props.position === 'right' && 'bj-drawer--right',
  props.size !== 'default' && `bj-drawer--${props.size}`,
])

const drawerId = computed(() => props.id || `bj-drawer-${++drawerUid}`)
const titleId = computed(() => `${drawerId.value}-title`)

function open() {
  previousFocus = document.activeElement as HTMLElement
  emit('update:modelValue', true)
  document.body.classList.add('bj-drawer-open')
}

function close() {
  emit('update:modelValue', false)
  document.body.classList.remove('bj-drawer-open')
  nextTick(() => previousFocus?.focus())
}

function onOverlayClick() {
  close()
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape' && props.modelValue) close()
}

watch(() => props.modelValue, (val) => {
  if (val) document.body.classList.add('bj-drawer-open')
  else document.body.classList.remove('bj-drawer-open')
})

onMounted(() => document.addEventListener('keydown', onKeydown))
onBeforeUnmount(() => {
  document.removeEventListener('keydown', onKeydown)
  document.body.classList.remove('bj-drawer-open')
})

defineExpose({ open, close })
</script>

<template>
  <div
    v-if="modelValue"
    ref="drawerRef"
    :id="drawerId"
    :class="classes"
    data-bj-expanded
    role="dialog"
    aria-modal="true"
    :aria-labelledby="title ? titleId : undefined"
    style="display: block"
  >
    <div class="bj-drawer__overlay" @click="onOverlayClick" />
    <div class="bj-drawer__panel">
      <header v-if="title || $slots.header" class="bj-drawer__header">
        <slot name="header">
          <h2 :id="titleId" class="bj-drawer__title">{{ title }}</h2>
        </slot>
        <button type="button" class="bj-drawer__close" :aria-label="closeLabel" @click="close">
          <BjSvgIcon name="closeLine" />
        </button>
      </header>
      <div class="bj-drawer__body">
        <slot />
      </div>
      <footer v-if="$slots.footer" class="bj-drawer__footer">
        <slot name="footer" :close="close" />
      </footer>
    </div>
  </div>
</template>

// src/react/components/BjDrawer.tsx
import { useEffect, useId, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { BjSvgIcon } from '../icons'

export interface BjDrawerProps {
  open: boolean
  onClose: () => void
  position?: 'left' | 'right'
  size?: 'default' | 'sm' | 'lg' | 'full'
  title?: string
  children?: ReactNode
  footer?: ReactNode
  className?: string
}

export function BjDrawer({
  open,
  onClose,
  position = 'left',
  size = 'default',
  title,
  children,
  footer,
  className,
}: BjDrawerProps) {
  const baseId = useId()
  const drawerId = `bj-drawer-${baseId.replace(/:/g, '')}`
  const titleId = `${drawerId}-title`

  useEffect(() => {
    if (open) document.body.classList.add('bj-drawer-open')
    else document.body.classList.remove('bj-drawer-open')
    return () => document.body.classList.remove('bj-drawer-open')
  }, [open])

  useEffect(() => {
    if (!open) return
    const onEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', onEsc)
    return () => document.removeEventListener('keydown', onEsc)
  }, [open, onClose])

  if (!open) return null

  const node = (
    <div
      id={drawerId}
      className={[
        'bj-drawer',
        position === 'right' && 'bj-drawer--right',
        size !== 'default' && `bj-drawer--${size}`,
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      data-bj-expanded
      role="dialog"
      aria-modal="true"
      aria-labelledby={title ? titleId : undefined}
      style={{ display: 'block' }}
    >
      <div className="bj-drawer__overlay" role="presentation" onClick={onClose} />
      <div className="bj-drawer__panel">
        {title ? (
          <header className="bj-drawer__header">
            <h2 id={titleId} className="bj-drawer__title">
              {title}
            </h2>
            <button type="button" className="bj-drawer__close" aria-label="Fermer" onClick={onClose}>
              <BjSvgIcon name="closeLine" />
            </button>
          </header>
        ) : null}
        <div className="bj-drawer__body">{children}</div>
        {footer ? <footer className="bj-drawer__footer">{footer}</footer> : null}
      </div>
    </div>
  )

  return createPortal(node, document.body)
}

BjDrawer.displayName = 'BjDrawer'
