// src/vue/components/BjNavigation.vue
<script lang="ts">
export interface BjNavigationProps {
  ariaLabel?: string
}
</script>

<script setup lang="ts">

withDefaults(defineProps<BjNavigationProps>(), {
  ariaLabel: 'Navigation',
})
</script>

<template>
  <nav class="bj-nav" :aria-label="ariaLabel" v-bind="$attrs">
    <ul class="bj-nav__list">
      <slot />
    </ul>
  </nav>
</template>

// src/react/components/BjNavigation.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react'

export type BjNavigationProps = {
  ariaLabel?: string
  children?: ReactNode
} & ComponentPropsWithoutRef<'nav'>

export function BjNavigation({ ariaLabel = 'Navigation', children, className, ...rest }: BjNavigationProps) {
  return (
    <nav
      className={['bj-nav', className].filter(Boolean).join(' ')}
      aria-label={ariaLabel}
      {...rest}
    >
      <ul className="bj-nav__list">{children}</ul>
    </nav>
  )
}

BjNavigation.displayName = 'BjNavigation'
