// src/vue/components/BjNotice.vue
<script lang="ts">
export interface BjNoticeProps {
  variant?: 'default' | 'info' | 'warning' | 'alert'
  closable?: boolean
  title?: string
  icon?: string
  closeLabel?: string
  role?: 'alert' | 'status'
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { BjSvgIcon, iconPaths } from '../icons'

const props = withDefaults(defineProps<BjNoticeProps>(), {
  variant: 'default',
  closeLabel: 'Fermer',
})

const emit = defineEmits<{ close: [] }>()

const visible = ref(true)

function remixClassToIconName(classStr: string): string | undefined {
  const m = classStr.match(/\bri-([a-z0-9]+(?:-[a-z0-9]+)*)\b/)
  if (!m) return undefined
  const segs = m[1].split('-')
  return segs[0] + segs.slice(1).map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('')
}

const noticeIconSvgName = computed(() => {
  if (!props.icon) return undefined
  const name = remixClassToIconName(props.icon)
  if (name && name in iconPaths) return name
  return undefined
})

const noticeIconExtraClass = computed(() => {
  if (!props.icon || !noticeIconSvgName.value) return ''
  return props.icon
    .trim()
    .split(/\s+/)
    .filter((c) => c && !c.startsWith('ri-'))
    .join(' ')
})

const effectiveRole = computed(() => {
  if (props.role) return props.role
  if (props.variant === 'alert' || props.variant === 'warning') return 'alert' as const
  return 'status' as const
})

const classes = computed(() => [
  'bj-notice',
  props.variant !== 'default' && `bj-notice--${props.variant}`,
])

function close() {
  visible.value = false
  emit('close')
}
</script>

<template>
  <div v-if="visible" :class="classes" :role="effectiveRole" v-bind="$attrs">
    <span
      v-if="icon && noticeIconSvgName"
      class="bj-notice__icon"
      :class="noticeIconExtraClass"
      aria-hidden="true"
    >
      <BjSvgIcon :name="noticeIconSvgName" />
    </span>
    <i v-else-if="icon" class="bj-notice__icon" :class="icon" aria-hidden="true" />
    <div class="bj-notice__body">
      <p v-if="title" class="bj-notice__title">{{ title }}</p>
      <slot />
    </div>
    <button
      v-if="closable"
      type="button"
      class="bj-notice__close"
      :aria-label="closeLabel"
      @click="close"
    >
      <BjSvgIcon name="closeLine" />
    </button>
  </div>
</template>

// src/react/components/BjNotice.tsx
import { useState, type HTMLAttributes, type ReactNode } from 'react'

import { BjSvgIcon, iconPaths, remixClassToIconName } from '../icons'

function classesWithoutRemixIcon(classes: string): string {
  return classes.replace(/\bri-[a-z0-9-]+\b/g, '').trim().replace(/\s+/g, ' ')
}

function noticeIconName(icon: string): string {
  if (!/\bri-[a-z0-9-]+/.test(icon)) return 'informationLine'
  const name = remixClassToIconName(icon)
  return name in iconPaths ? name : 'informationLine'
}

export interface BjNoticeProps extends Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'title' | 'role'> {
  variant?: 'default' | 'info' | 'warning' | 'alert'
  closable?: boolean
  closeLabel?: string
  title?: string
  icon?: string
  role?: 'alert' | 'status'
  onClose?: () => void
  children?: ReactNode
}

export function BjNotice({
  variant = 'default',
  closable,
  closeLabel = 'Fermer',
  title,
  icon,
  role: roleProp,
  onClose,
  className,
  children,
  ...rest
}: BjNoticeProps) {
  const [visible, setVisible] = useState(true)

  const effectiveRole = roleProp ?? (variant === 'alert' || variant === 'warning' ? 'alert' : 'status')

  const cls = ['bj-notice', variant !== 'default' && `bj-notice--${variant}`, className]
    .filter(Boolean)
    .join(' ')

  function close() {
    setVisible(false)
    onClose?.()
  }

  if (!visible) return null

  return (
    <div className={cls} role={effectiveRole} {...rest}>
      {icon ? (
        <span
          className={['bj-notice__icon', classesWithoutRemixIcon(icon)].filter(Boolean).join(' ')}
          aria-hidden="true"
        >
          <BjSvgIcon name={noticeIconName(icon)} />
        </span>
      ) : null}
      <div className="bj-notice__body">
        {title ? <p className="bj-notice__title">{title}</p> : null}
        {children}
      </div>
      {closable ? (
        <button type="button" className="bj-notice__close" aria-label={closeLabel} onClick={close}>
          <BjSvgIcon name="closeLine" />
        </button>
      ) : null}
    </div>
  )
}
BjNotice.displayName = 'BjNotice'
