// src/vue/components/BjPagination.vue
<script lang="ts">
export interface BjPaginationProps {
  modelValue: number
  total: number
  perPage?: number
  maxVisible?: number
  ariaLabel?: string
  prevLabel?: string
  nextLabel?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { BjSvgIcon } from '../icons'

const props = withDefaults(defineProps<BjPaginationProps>(), {
  perPage: 10,
  maxVisible: 5,
  ariaLabel: 'Pagination',
  prevLabel: 'Page précédente',
  nextLabel: 'Page suivante',
})

const emit = defineEmits<{
  'update:modelValue': [page: number]
}>()

const totalPages = computed(() => Math.max(1, Math.ceil(props.total / props.perPage)))

const pages = computed(() => {
  const result: (number | '...')[] = []
  const total = totalPages.value
  const current = props.modelValue
  const half = Math.floor(props.maxVisible / 2)

  let start = Math.max(1, current - half)
  let end = Math.min(total, start + props.maxVisible - 1)

  if (end - start + 1 < props.maxVisible) {
    start = Math.max(1, end - props.maxVisible + 1)
  }

  if (start > 1) {
    result.push(1)
    if (start > 2) result.push('...')
  }

  for (let i = start; i <= end; i++) result.push(i)

  if (end < total) {
    if (end < total - 1) result.push('...')
    result.push(total)
  }

  return result
})

function go(page: number) {
  if (page >= 1 && page <= totalPages.value && page !== props.modelValue) {
    emit('update:modelValue', page)
  }
}
</script>

<template>
  <nav class="bj-pagination" :aria-label="ariaLabel" v-bind="$attrs">
    <button
      type="button"
      class="bj-pagination__nav"
      :class="{ 'bj-pagination__nav--disabled': modelValue <= 1 }"
      :disabled="modelValue <= 1"
      :aria-label="prevLabel"
      @click="go(modelValue - 1)"
    >
      <BjSvgIcon name="arrowLeftSLine" />
    </button>
    <template v-for="(p, i) in pages" :key="i">
      <span v-if="p === '...'" class="bj-pagination__ellipsis" aria-hidden="true">...</span>
      <button
        v-else
        type="button"
        class="bj-pagination__link"
        :class="{ 'bj-pagination__link--active': p === modelValue }"
        :aria-current="p === modelValue ? 'page' : undefined"
        :aria-label="`Page ${p}`"
        @click="go(p as number)"
      >
        {{ p }}
      </button>
    </template>
    <button
      type="button"
      class="bj-pagination__nav"
      :class="{ 'bj-pagination__nav--disabled': modelValue >= totalPages }"
      :disabled="modelValue >= totalPages"
      :aria-label="nextLabel"
      @click="go(modelValue + 1)"
    >
      <BjSvgIcon name="arrowRightSLine" />
    </button>
  </nav>
</template>

// src/react/components/BjPagination.tsx
import { useMemo, type ComponentPropsWithoutRef } from 'react'

import { BjSvgIcon } from '../icons'

export type BjPaginationProps = Omit<ComponentPropsWithoutRef<'nav'>, 'onChange'> & {
  page: number
  total: number
  perPage?: number
  maxVisible?: number
  ariaLabel?: string
  prevLabel?: string
  nextLabel?: string
  onChange: (page: number) => void
}

function buildPages(current: number, total: number, maxVisible: number): (number | '...')[] {
  const result: (number | '...')[] = []
  const half = Math.floor(maxVisible / 2)

  let start = Math.max(1, current - half)
  let end = Math.min(total, start + maxVisible - 1)

  if (end - start + 1 < maxVisible) {
    start = Math.max(1, end - maxVisible + 1)
  }

  if (start > 1) {
    result.push(1)
    if (start > 2) result.push('...')
  }

  for (let i = start; i <= end; i++) result.push(i)

  if (end < total) {
    if (end < total - 1) result.push('...')
    result.push(total)
  }

  return result
}

export function BjPagination({
  page,
  total,
  perPage = 10,
  maxVisible = 5,
  ariaLabel = 'Pagination',
  prevLabel = 'Page précédente',
  nextLabel = 'Page suivante',
  onChange,
  className,
  ...rest
}: BjPaginationProps) {
  const totalPages = total > 0 ? Math.ceil(total / perPage) : 0

  const pages = useMemo(
    () => (totalPages > 0 ? buildPages(page, totalPages, maxVisible) : []),
    [page, totalPages, maxVisible],
  )

  function go(nextPage: number) {
    if (nextPage >= 1 && nextPage <= totalPages && nextPage !== page) {
      onChange(nextPage)
    }
  }

  return (
    <nav
      className={['bj-pagination', className].filter(Boolean).join(' ')}
      aria-label={ariaLabel}
      {...rest}
    >
      <button
        type="button"
        className={['bj-pagination__nav', page <= 1 && 'bj-pagination__nav--disabled']
          .filter(Boolean)
          .join(' ')}
        disabled={page <= 1}
        aria-label={prevLabel}
        onClick={() => go(page - 1)}
      >
        <BjSvgIcon name="arrowLeftSLine" />
      </button>
      {pages.map((p, i) =>
        p === '...' ? (
          <span key={`e-${i}`} className="bj-pagination__ellipsis" aria-hidden="true">
            ...
          </span>
        ) : (
          <button
            key={p}
            type="button"
            className={['bj-pagination__link', p === page && 'bj-pagination__link--active']
              .filter(Boolean)
              .join(' ')}
            aria-current={p === page ? 'page' : undefined}
            aria-label={`Page ${p}`}
            onClick={() => go(p)}
          >
            {p}
          </button>
        ),
      )}
      <button
        type="button"
        className={['bj-pagination__nav', page >= totalPages && 'bj-pagination__nav--disabled']
          .filter(Boolean)
          .join(' ')}
        disabled={page >= totalPages || totalPages === 0}
        aria-label={nextLabel}
        onClick={() => go(page + 1)}
      >
        <BjSvgIcon name="arrowRightSLine" />
      </button>
    </nav>
  )
}

BjPagination.displayName = 'BjPagination'
