// src/vue/components/BjSearch.vue
<script lang="ts">
export interface BjSearchProps {
  modelValue?: string
  placeholder?: string
  size?: 'md' | 'lg'
  buttonLabel?: string
  label?: string
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { BjSvgIcon } from '../icons'

let uid = 0

const props = withDefaults(defineProps<BjSearchProps>(), {
  modelValue: '',
  placeholder: 'Rechercher…',
  size: 'md',
  buttonLabel: 'Rechercher',
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  submit: [value: string]
}>()

const inputId = `bj-search-${++uid}`

const classes = computed(() => [
  'bj-search',
  props.size === 'lg' && 'bj-search--lg',
])

function onInput(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).value)
}

function onSubmit() {
  emit('submit', props.modelValue)
}
</script>

<template>
  <form :class="classes" role="search" @submit.prevent="onSubmit">
    <label v-if="label" class="bj-search__label bj-sr-only" :for="inputId">{{ label }}</label>
    <input
      :id="inputId"
      class="bj-search__input"
      type="search"
      :value="modelValue"
      :placeholder="placeholder"
      :aria-label="!label ? placeholder : undefined"
      v-bind="$attrs"
      @input="onInput"
    />
    <button type="submit" class="bj-search__btn">
      <slot>
        <BjSvgIcon name="searchLine" />
        <span>{{ buttonLabel }}</span>
      </slot>
    </button>
  </form>
</template>

// src/react/components/BjSearch.tsx
import { useId } from 'react'
import type * as React from 'react'

import { BjSvgIcon } from '../icons'

export interface BjSearchProps
  extends Omit<React.FormHTMLAttributes<HTMLFormElement>, 'onSubmit' | 'children' | 'role' | 'onChange'> {
  value?: string
  onChange?: React.ChangeEventHandler<HTMLInputElement>
  onSubmit?: (value: string) => void
  placeholder?: string
  size?: 'md' | 'lg'
  buttonLabel?: string
  label?: string
  id?: string
  children?: React.ReactNode
}

export function BjSearch({
  value = '',
  onChange,
  onSubmit,
  placeholder = 'Rechercher…',
  size = 'md',
  buttonLabel = 'Rechercher',
  label,
  id: idProp,
  className,
  children,
  ...rest
}: BjSearchProps) {
  const uid = useId()
  const inputId = idProp ?? `bj-search-${uid.replace(/:/g, '')}`
  const formClass = ['bj-search', size === 'lg' && 'bj-search--lg', className].filter(Boolean).join(' ')

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    onSubmit?.(value)
  }

  return (
    <form className={formClass} role="search" onSubmit={handleSubmit} {...rest}>
      {label ? (
        <label className="sr-only" htmlFor={inputId}>{label}</label>
      ) : null}
      <input
        id={inputId}
        className="bj-search__input"
        type="search"
        value={value}
        placeholder={placeholder}
        aria-label={!label ? placeholder : undefined}
        onChange={onChange}
      />
      <button type="submit" className="bj-search__btn">
        {children ?? (
          <>
            <BjSvgIcon name="searchLine" />
            <span>{buttonLabel}</span>
          </>
        )}
      </button>
    </form>
  )
}

BjSearch.displayName = 'BjSearch'
