// src/vue/components/BjSkiplink.vue
<script lang="ts">
export interface SkiplinkItem {
  label: string
  target: string
}
export interface BjSkiplinkProps {
  links?: SkiplinkItem[]
}
</script>

<script setup lang="ts">

const props = withDefaults(defineProps<BjSkiplinkProps>(), {
  links: () => [{ label: 'Aller au contenu', target: '#main' }],
})
</script>

<template>
  <div class="bj-skiplinks" v-bind="$attrs">
    <div class="bj-skiplinks__list">
      <a v-for="link in links" :key="link.target" class="bj-skiplinks__link" :href="link.target">
        {{ link.label }}
      </a>
    </div>
  </div>
</template>

// src/react/components/BjSkiplink.tsx
import type { ComponentPropsWithoutRef } from 'react'

export type BjSkiplinkLink = {
  label: string
  target: string
}

export type BjSkiplinkProps = {
  links?: BjSkiplinkLink[]
} & ComponentPropsWithoutRef<'div'>

export function BjSkiplink({
  links = [{ label: 'Aller au contenu', target: '#main' }],
  className,
  ...rest
}: BjSkiplinkProps) {
  return (
    <div className={['bj-skiplinks', className].filter(Boolean).join(' ')} {...rest}>
      <div className="bj-skiplinks__list">
        {links.map((link) => (
          <a key={link.target} className="bj-skiplinks__link" href={link.target}>
            {link.label}
          </a>
        ))}
      </div>
    </div>
  )
}

BjSkiplink.displayName = 'BjSkiplink'
