// src/vue/components/BjSkeleton.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface BjSkeletonProps {
  variant?: 'text' | 'heading' | 'circle' | 'rect'
  size?: 'sm' | 'md' | 'lg'
}

const props = withDefaults(defineProps<BjSkeletonProps>(), {
  variant: 'text',
  size: 'md',
})

const classes = computed(() => [
  'bj-skeleton',
  `bj-skeleton--${props.variant}`,
  props.size !== 'md' && `bj-skeleton--${props.size}`,
])
</script>

<template>
  <div :class="classes" aria-hidden="true" v-bind="$attrs" />
</template>

// src/react/components/BjSkeleton.tsx
import type { ComponentPropsWithoutRef } from 'react'

export type BjSkeletonProps = {
  variant?: 'text' | 'heading' | 'circle' | 'rect'
  size?: 'sm' | 'md' | 'lg'
} & ComponentPropsWithoutRef<'div'>

export function BjSkeleton({
  variant = 'text',
  size = 'md',
  className,
  ...rest
}: BjSkeletonProps) {
  const cls = [
    'bj-skeleton',
    `bj-skeleton--${variant}`,
    size !== 'md' && `bj-skeleton--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return <div className={cls} aria-hidden="true" {...rest} />
}

BjSkeleton.displayName = 'BjSkeleton'
