// src/vue/components/BjTable.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface BjTableProps {
  bordered?: boolean
  striped?: boolean
  fixedLayout?: boolean
  caption?: string
}

const props = defineProps<BjTableProps>()

const classes = computed(() => [
  'bj-table',
  props.bordered && 'bj-table--bordered',
  props.striped && 'bj-table--striped',
  props.fixedLayout && 'bj-table--layout-fixed',
  !props.caption && 'bj-table--no-caption',
])
</script>

<template>
  <div class="bj-table-wrapper" v-bind="$attrs">
    <div v-if="$slots.header" class="bj-table__header">
      <slot name="header" />
    </div>
    <table :class="classes">
      <caption v-if="caption">{{ caption }}</caption>
      <slot />
    </table>
    <div v-if="$slots.footer" class="bj-table__footer">
      <slot name="footer" />
    </div>
  </div>
</template>

// src/react/components/BjTable.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react'

export type BjTableProps = {
  bordered?: boolean
  striped?: boolean
  fixedLayout?: boolean
  caption?: string
  header?: ReactNode
  footer?: ReactNode
  children?: ReactNode
} & ComponentPropsWithoutRef<'div'>

export function BjTable({
  bordered,
  striped,
  fixedLayout,
  caption,
  header,
  footer,
  children,
  className,
  ...rest
}: BjTableProps) {
  const tableCls = [
    'bj-table',
    bordered && 'bj-table--bordered',
    striped && 'bj-table--striped',
    fixedLayout && 'bj-table--layout-fixed',
    !caption && 'bj-table--no-caption',
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={['bj-table-wrapper', className].filter(Boolean).join(' ')} {...rest}>
      {header ? <div className="bj-table__header">{header}</div> : null}
      <table className={tableCls}>
        {caption ? <caption>{caption}</caption> : null}
        {children}
      </table>
      {footer ? <div className="bj-table__footer">{footer}</div> : null}
    </div>
  )
}

BjTable.displayName = 'BjTable'
