// src/vue/components/BjToast.vue
<script lang="ts">
import type { ToastPosition } from '../composables/useToast'

export interface BjToastProps {
  position?: ToastPosition
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { BjSvgIcon } from '../icons'
import { useToast, type ToastType } from '../composables/useToast'

const props = withDefaults(defineProps<BjToastProps>(), {
  position: 'top-right',
})

const { toasts, add, remove } = useToast()

const toastIconNames: Record<ToastType, string> = {
  info: 'informationLine',
  success: 'checkLine',
  warning: 'alertLine',
  error: 'closeCircleLine',
}

const containerClasses = computed(() => [
  'bj-toast-container',
  props.position !== 'top-right' && `bj-toast-container--${props.position}`,
])

defineExpose({ add, remove, toasts })
</script>

<template>
  <div :class="containerClasses" aria-live="polite" role="status">
    <div
      v-for="t in toasts"
      :key="t.id"
      class="bj-toast"
      :class="[
        `bj-toast--${t.type}`,
        t.removing && 'bj-toast--removing',
      ]"
      role="alert"
    >
      <span class="bj-toast__icon" aria-hidden="true">
        <BjSvgIcon :name="toastIconNames[t.type]" />
      </span>
      <div class="bj-toast__body">
        <p v-if="t.title" class="bj-toast__title">{{ t.title }}</p>
        <p class="bj-toast__text">{{ t.text }}</p>
      </div>
      <button type="button" class="bj-toast__close" aria-label="Fermer" @click="remove(t.id)">
        <BjSvgIcon name="closeLine" />
      </button>
      <div
        v-if="t.duration > 0"
        class="bj-toast__progress"
        :style="{
          width: '100%',
          transitionDuration: `${t.duration}ms`,
          animation: `bjProgressShrink ${t.duration}ms linear forwards`,
        }"
      />
    </div>
  </div>
</template>

// src/react/components/BjToast.tsx
import type { ToastItem, ToastPosition, ToastType } from '../hooks/useToast'
import { BjSvgIcon } from '../icons'

export interface BjToastProps {
  position?: ToastPosition
  toasts: ToastItem[]
  onRemove: (id: string) => void
  className?: string
}

const TOAST_ICONS: Record<ToastType, string> = {
  info: 'informationLine',
  success: 'checkLine',
  warning: 'alertLine',
  error: 'closeCircleLine',
}

export function BjToast({ position = 'top-right', toasts, onRemove, className }: BjToastProps) {
  return (
    <div
      className={[
        'bj-toast-container',
        position !== 'top-right' && `bj-toast-container--${position}`,
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      aria-live="polite"
      role="status"
    >
      {toasts.map(t => (
        <div
          key={t.id}
          className={['bj-toast', `bj-toast--${t.type}`, t.removing && 'bj-toast--removing']
            .filter(Boolean)
            .join(' ')}
          role="alert"
        >
          <span className="bj-toast__icon" aria-hidden="true">
            <BjSvgIcon name={TOAST_ICONS[t.type]} />
          </span>
          <div className="bj-toast__body">
            {t.title ? <p className="bj-toast__title">{t.title}</p> : null}
            <p className="bj-toast__text">{t.text}</p>
          </div>
          <button type="button" className="bj-toast__close" aria-label="Fermer" onClick={() => onRemove(t.id)}>
            <BjSvgIcon name="closeLine" />
          </button>
          {t.duration > 0 ? (
            <div
              className="bj-toast__progress"
              style={{
                width: '100%',
                transitionDuration: `${t.duration}ms`,
                animation: `bjProgressShrink ${t.duration}ms linear forwards`,
              }}
            />
          ) : null}
        </div>
      ))}
    </div>
  )
}

BjToast.displayName = 'BjToast'
