// src/vue/components/BjTooltip.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface BjTooltipProps {
  text: string
  position?: 'top' | 'bottom' | 'left' | 'right'
}

const props = withDefaults(defineProps<BjTooltipProps>(), {
  position: 'top',
})

const classes = computed(() => [
  'bj-tooltip',
  props.position !== 'top' && `bj-tooltip--${props.position}`,
])
</script>

<template>
  <span :class="classes" v-bind="$attrs">
    <slot />
    <span class="bj-tooltip__content" role="tooltip">{{ text }}</span>
  </span>
</template>

// src/react/components/BjTooltip.tsx
import { type ReactNode } from 'react'

export interface BjTooltipProps {
  text: string
  position?: 'top' | 'bottom' | 'left' | 'right'
  children?: ReactNode
  className?: string
}

export function BjTooltip({ text, position = 'top', children, className }: BjTooltipProps) {
  return (
    <span
      className={[
        'bj-tooltip',
        position !== 'top' && `bj-tooltip--${position}`,
        className,
      ]
        .filter(Boolean)
        .join(' ')}
    >
      {children}
      <span className="bj-tooltip__content" role="tooltip">
        {text}
      </span>
    </span>
  )
}

BjTooltip.displayName = 'BjTooltip'
